/* MATHIA — zajednički prevod "okvira" (meni, footer, dugmad, nazivi predmeta, tipovi materijala).
   Prevodi tekstualne čvorove koji se TAČNO poklapaju sa srpskim izvorom. Bezbedno: čuva original, vraća na 'sr'. */
(function(){
  var D = {
    // ——— footer / okvir ———
    "Uči s ljubavlju":{en:"Learn with love",de:"Lerne mit Liebe",fr:"Apprends avec amour",es:"Aprende con amor",it:"Impara con amore",ru:"Учись с любовью",pt:"Aprende com amor"},
    "Tvoja profesorica":{en:"Your teacher",de:"Deine Lehrerin",fr:"Ta professeure",es:"Tu profesora",it:"La tua insegnante",ru:"Твоя преподавательница",pt:"A tua professora"},
    "← Mathia · Početna":{en:"← Mathia · Home",de:"← Mathia · Start",fr:"← Mathia · Accueil",es:"← Mathia · Inicio",it:"← Mathia · Home",ru:"← Mathia · Главная",pt:"← Mathia · Início"},
    "Početna":{en:"Home",de:"Start",fr:"Accueil",es:"Inicio",it:"Home",ru:"Главная",pt:"Início"},
    "Nazad na početnu":{en:"Back to home",de:"Zurück zur Startseite",fr:"Retour à l’accueil",es:"Volver al inicio",it:"Torna alla home",ru:"На главную",pt:"Voltar ao início"},
    "Nazad na predmete":{en:"Back to subjects",de:"Zurück zu den Fächern",fr:"Retour aux matières",es:"Volver a las asignaturas",it:"Torna alle materie",ru:"Назад к предметам",pt:"Voltar às disciplinas"},
    "© 2026 Mathia Edu · Sva prava zadržana. Zabranjeno je kopiranje, umnožavanje i distribucija sadržaja, dizajna i metodologije bez pismene dozvole.":{en:"© 2026 Mathia Edu · All rights reserved. Copying, reproduction and distribution of content, design and methodology without written permission is prohibited.",de:"© 2026 Mathia Edu · Alle Rechte vorbehalten. Kopieren, Vervielfältigen und Verbreiten von Inhalt, Design und Methodik ohne schriftliche Genehmigung ist untersagt.",fr:"© 2026 Mathia Edu · Tous droits réservés. La copie, la reproduction et la distribution du contenu, du design et de la méthodologie sans autorisation écrite sont interdites.",es:"© 2026 Mathia Edu · Todos los derechos reservados. Se prohíbe copiar, reproducir y distribuir el contenido, el diseño y la metodología sin autorización por escrito.",it:"© 2026 Mathia Edu · Tutti i diritti riservati. È vietata la copia, la riproduzione e la distribuzione di contenuti, design e metodologia senza autorizzazione scritta.",ru:"© 2026 Mathia Edu · Все права защищены. Копирование, воспроизведение и распространение содержимого, дизайна и методологии без письменного разрешения запрещены.",pt:"© 2026 Mathia Edu · Todos os direitos reservados. É proibida a cópia, reprodução e distribuição de conteúdo, design e metodologia sem autorização escrita."},
    // ——— tipovi materijala ———
    "Skripta":{en:"Notes",de:"Skript",fr:"Cours",es:"Apuntes",it:"Dispensa",ru:"Конспект",pt:"Apontamentos"},
    "Formule":{en:"Formulas",de:"Formeln",fr:"Formules",es:"Fórmulas",it:"Formule",ru:"Формулы",pt:"Fórmulas"},
    "Zadaci":{en:"Problems",de:"Aufgaben",fr:"Exercices",es:"Problemas",it:"Esercizi",ru:"Задачи",pt:"Exercícios"},
    "Priručnik":{en:"Handbook",de:"Handbuch",fr:"Manuel",es:"Manual",it:"Manuale",ru:"Справочник",pt:"Manual"},
    "Skripta — Teorija, metode i rešeni primeri":{en:"Notes — theory, methods and worked examples",de:"Skript — Theorie, Methoden und gelöste Beispiele",fr:"Cours — théorie, méthodes et exemples résolus",es:"Apuntes — teoría, métodos y ejemplos resueltos",it:"Dispensa — teoria, metodi ed esempi svolti",ru:"Конспект — теория, методы и разобранные примеры",pt:"Apontamentos — teoria, métodos e exemplos resolvidos"},
    // ——— česta dugmad ———
    "Otvori skriptu":{en:"Open the notes",de:"Skript öffnen",fr:"Ouvrir le cours",es:"Abrir apuntes",it:"Apri la dispensa",ru:"Открыть конспект",pt:"Abrir apontamentos"},
    "Otvori formule":{en:"Open formulas",de:"Formeln öffnen",fr:"Ouvrir les formules",es:"Abrir fórmulas",it:"Apri le formule",ru:"Открыть формулы",pt:"Abrir fórmulas"},
    "Otvori zadatke":{en:"Open problems",de:"Aufgaben öffnen",fr:"Ouvrir les exercices",es:"Abrir problemas",it:"Apri gli esercizi",ru:"Открыть задачи",pt:"Abrir exercícios"},
    "Započni besplatno →":{en:"Start free →",de:"Kostenlos starten →",fr:"Commence gratuitement →",es:"Empieza gratis →",it:"Inizia gratis →",ru:"Начать бесплатно →",pt:"Começa grátis →"},
    "Uradi test sklonosti →":{en:"Take the aptitude test →",de:"Mach den Eignungstest →",fr:"Fais le test d’aptitude →",es:"Haz el test de aptitud →",it:"Fai il test attitudinale →",ru:"Пройди тест на склонности →",pt:"Faz o teste de aptidão →"},
    // ——— nazivi predmeta (najčešći) ———
    "Mala matura":{en:"Final exam (grade 8)",de:"Abschlussprüfung",fr:"Brevet",es:"Examen final",it:"Esame di terza media",ru:"Выпускной экзамен",pt:"Exame final"},
    "Matematička analiza 1":{en:"Calculus 1",de:"Analysis 1",fr:"Analyse 1",es:"Cálculo 1",it:"Analisi matematica 1",ru:"Математический анализ 1",pt:"Cálculo 1"},
    "Matematička analiza 2":{en:"Calculus 2",de:"Analysis 2",fr:"Analyse 2",es:"Cálculo 2",it:"Analisi matematica 2",ru:"Математический анализ 2",pt:"Cálculo 2"},
    "Linearna algebra":{en:"Linear algebra",de:"Lineare Algebra",fr:"Algèbre linéaire",es:"Álgebra lineal",it:"Algebra lineare",ru:"Линейная алгебра",pt:"Álgebra linear"},
    "Diskretna matematika":{en:"Discrete mathematics",de:"Diskrete Mathematik",fr:"Mathématiques discrètes",es:"Matemática discreta",it:"Matematica discreta",ru:"Дискретная математика",pt:"Matemática discreta"},
    "Kompleksna analiza":{en:"Complex analysis",de:"Funktionentheorie",fr:"Analyse complexe",es:"Análisis complejo",it:"Analisi complessa",ru:"Комплексный анализ",pt:"Análise complexa"},
    "Verovatnoća i statistika":{en:"Probability & statistics",de:"Wahrscheinlichkeit & Statistik",fr:"Probabilités & statistiques",es:"Probabilidad y estadística",it:"Probabilità e statistica",ru:"Теория вероятностей и статистика",pt:"Probabilidade e estatística"},
    "Operaciona istraživanja":{en:"Operations research",de:"Operations Research",fr:"Recherche opérationnelle",es:"Investigación operativa",it:"Ricerca operativa",ru:"Исследование операций",pt:"Investigação operacional"},
    "Teorija električnih kola":{en:"Electric circuit theory",de:"Theorie elektrischer Schaltungen",fr:"Théorie des circuits électriques",es:"Teoría de circuitos eléctricos",it:"Teoria dei circuiti elettrici",ru:"Теория электрических цепей",pt:"Teoria de circuitos elétricos"},
    "Električna merenja":{en:"Electrical measurements",de:"Elektrische Messtechnik",fr:"Mesures électriques",es:"Mediciones eléctricas",it:"Misure elettriche",ru:"Электрические измерения",pt:"Medições elétricas"},
    "Uvod u elektroniku":{en:"Introduction to electronics",de:"Einführung in die Elektronik",fr:"Introduction à l’électronique",es:"Introducción a la electrónica",it:"Introduzione all’elettronica",ru:"Введение в электронику",pt:"Introdução à eletrónica"},
    "Elektromagnetika":{en:"Electromagnetics",de:"Elektromagnetismus",fr:"Électromagnétisme",es:"Electromagnetismo",it:"Elettromagnetismo",ru:"Электромагнетизм",pt:"Eletromagnetismo"},
    "Mehanika":{en:"Mechanics",de:"Mechanik",fr:"Mécanique",es:"Mecánica",it:"Meccanica",ru:"Механика",pt:"Mecânica"},
    "Arhitektura računara":{en:"Computer architecture",de:"Rechnerarchitektur",fr:"Architecture des ordinateurs",es:"Arquitectura de computadores",it:"Architettura dei calcolatori",ru:"Архитектура компьютеров",pt:"Arquitetura de computadores"},
    "Algebra":{en:"Algebra",de:"Algebra",fr:"Algèbre",es:"Álgebra",it:"Algebra",ru:"Алгебра",pt:"Álgebra"},
    "Početna strana":{"en": "Home page", "de": "Startseite", "fr": "Page d’accueil", "es": "Página de inicio", "it": "Pagina iniziale", "ru": "Главная страница", "pt": "Página inicial"},
    "Uslovi kupovine":{"en": "Terms of purchase", "de": "Kaufbedingungen", "fr": "Conditions d’achat", "es": "Condiciones de compra", "it": "Condizioni d’acquisto", "ru": "Условия покупки", "pt": "Condições de compra"},
    "Reklamacije i povraćaj":{"en": "Complaints & returns", "de": "Reklamationen & Rückgabe", "fr": "Réclamations & retours", "es": "Reclamaciones y devoluciones", "it": "Reclami e resi", "ru": "Жалобы и возврат", "pt": "Reclamações e devoluções"},
    "Politika privatnosti":{"en": "Privacy policy", "de": "Datenschutz", "fr": "Confidentialité", "es": "Política de privacidad", "it": "Privacy", "ru": "Политика конфиденциальности", "pt": "Política de privacidade"},
    "Internet:":{"en": "Website:", "de": "Internet:", "fr": "Site web :", "es": "Web:", "it": "Sito:", "ru": "Сайт:", "pt": "Site:"},
    "Delatnost: 8559 — Ostalo obrazovanje":{"en": "Activity: 8559 — Other education", "de": "Tätigkeit: 8559 — Sonstige Bildung", "fr": "Activité : 8559 — Autre enseignement", "es": "Actividad: 8559 — Otra educación", "it": "Attività: 8559 — Altra istruzione", "ru": "Деятельность: 8559 — Прочее образование", "pt": "Atividade: 8559 — Outra educação"},
    "Plaćanje karticama je zaštićeno 3-D Secure programom (Visa Secure i Mastercard ID Check). Podatke o kartici unosite isključivo na bezbednoj stranici banke — Mathia ih ne vidi niti čuva. Sve cene su iskazane u dinarima (RSD).":{"en": "Card payments are protected by 3-D Secure (Visa Secure and Mastercard ID Check). Card details are entered only on the bank’s secure page — Mathia neither sees nor stores them. All prices are shown in dinars (RSD).", "de": "Kartenzahlungen sind durch 3-D Secure geschützt (Visa Secure und Mastercard ID Check). Kartendaten werden ausschließlich auf der sicheren Bankseite eingegeben — Mathia sieht und speichert sie nicht. Alle Preise sind in Dinar (RSD) angegeben.", "fr": "Les paiements par carte sont protégés par 3-D Secure (Visa Secure et Mastercard ID Check). Les données de la carte sont saisies uniquement sur la page sécurisée de la banque — Mathia ne les voit ni ne les conserve. Tous les prix sont en dinars (RSD).", "es": "Los pagos con tarjeta están protegidos por 3-D Secure (Visa Secure y Mastercard ID Check). Los datos de la tarjeta se introducen solo en la página segura del banco — Mathia no los ve ni los guarda. Todos los precios se muestran en dinares (RSD).", "it": "I pagamenti con carta sono protetti da 3-D Secure (Visa Secure e Mastercard ID Check). I dati della carta si inseriscono solo sulla pagina sicura della banca — Mathia non li vede né li conserva. Tutti i prezzi sono in dinari (RSD).", "ru": "Оплата картой защищена 3-D Secure (Visa Secure и Mastercard ID Check). Данные карты вводятся только на защищённой странице банка — Mathia их не видит и не хранит. Все цены указаны в динарах (RSD).", "pt": "Os pagamentos com cartão são protegidos por 3-D Secure (Visa Secure e Mastercard ID Check). Os dados do cartão são introduzidos apenas na página segura do banco — a Mathia não os vê nem guarda. Todos os preços são em dinares (RSD)."},
    "Hvala na kupovini!":{"en": "Thank you for your purchase!", "de": "Danke für deinen Kauf!", "fr": "Merci pour ton achat !", "es": "¡Gracias por tu compra!", "it": "Grazie per l’acquisto!", "ru": "Спасибо за покупку!", "pt": "Obrigada pela compra!"},
    "Vaše plaćanje je uspešno primljeno. Pristup je aktiviran, a fiskalni račun i potvrda stižu na vaš e-mail.":{"en": "Your payment was received successfully. Access is activated, and the receipt and confirmation are on their way to your email.", "de": "Deine Zahlung ist erfolgreich eingegangen. Der Zugang ist aktiviert, Beleg und Bestätigung kommen per E-Mail.", "fr": "Ton paiement a bien été reçu. L’accès est activé, et le reçu et la confirmation arrivent par e-mail.", "es": "Tu pago se recibió correctamente. El acceso está activado y el recibo y la confirmación llegarán a tu correo.", "it": "Il pagamento è stato ricevuto correttamente. L’accesso è attivo e ricevuta e conferma arrivano via e-mail.", "ru": "Оплата успешно получена. Доступ активирован, чек и подтверждение придут на e-mail.", "pt": "O teu pagamento foi recebido com sucesso. O acesso está ativado e o recibo e a confirmação chegam ao teu email."},
    "Idi na moj nalog":{"en": "Go to my account", "de": "Zu meinem Konto", "fr": "Aller à mon compte", "es": "Ir a mi cuenta", "it": "Vai al mio account", "ru": "Перейти в личный кабинет", "pt": "Ir para a minha conta"},
    "Ako vam račun ne stigne u roku od nekoliko minuta, proverite „spam\" folder ili nas kontaktirajte na":{"en": "If the receipt doesn’t arrive within a few minutes, check your “spam” folder or contact us at", "de": "Falls der Beleg nicht in wenigen Minuten ankommt, prüfe den „Spam“-Ordner oder kontaktiere uns unter", "fr": "Si le reçu n’arrive pas en quelques minutes, vérifie le dossier « spam » ou écris-nous à", "es": "Si el recibo no llega en unos minutos, revisa la carpeta de “spam” o contáctanos en", "it": "Se la ricevuta non arriva in pochi minuti, controlla la cartella “spam” o scrivici a", "ru": "Если чек не придёт в течение нескольких минут, проверьте папку «спам» или напишите нам на", "pt": "Se o recibo não chegar em poucos minutos, verifica a pasta “spam” ou contacta-nos em"},
    "Plaćanje nije uspelo":{"en": "Payment failed", "de": "Zahlung fehlgeschlagen", "fr": "Le paiement a échoué", "es": "El pago falló", "it": "Pagamento non riuscito", "ru": "Оплата не удалась", "pt": "O pagamento falhou"},
    "Transakcija nije završena i":{"en": "The transaction wasn’t completed and", "de": "Die Transaktion wurde nicht abgeschlossen und", "fr": "La transaction n’a pas abouti et", "es": "La transacción no se completó y", "it": "La transazione non è stata completata e", "ru": "Транзакция не завершена, и", "pt": "A transação não foi concluída e"},
    "ništa vam nije naplaćeno":{"en": "you weren’t charged anything", "de": "dir wurde nichts berechnet", "fr": "rien ne t’a été facturé", "es": "no se te cobró nada", "it": "non ti è stato addebitato nulla", "ru": "с вас ничего не списано", "pt": "não te foi cobrado nada"},
    ". Ovo se ponekad dešava zbog banke, unosa podataka ili prekida veze.":{"en": ". This sometimes happens due to the bank, entered details or a lost connection.", "de": ". Das passiert manchmal wegen der Bank, der Eingabe oder einer unterbrochenen Verbindung.", "fr": ". Cela arrive parfois à cause de la banque, des données saisies ou d’une connexion interrompue.", "es": ". Esto ocurre a veces por el banco, los datos introducidos o una conexión interrumpida.", "it": ". A volte succede a causa della banca, dei dati inseriti o di una connessione interrotta.", "ru": ". Иногда это происходит из-за банка, введённых данных или обрыва связи.", "pt": ". Às vezes acontece devido ao banco, aos dados inseridos ou a uma ligação interrompida."},
    "Pokušaj ponovo":{"en": "Try again", "de": "Erneut versuchen", "fr": "Réessayer", "es": "Inténtalo de nuevo", "it": "Riprova", "ru": "Попробовать снова", "pt": "Tentar de novo"},
    "Ako se problem ponavlja, pišite nam na":{"en": "If the problem persists, write to us at", "de": "Wenn das Problem weiterhin besteht, schreib uns an", "fr": "Si le problème persiste, écris-nous à", "es": "Si el problema continúa, escríbenos a", "it": "Se il problema persiste, scrivici a", "ru": "Если проблема повторяется, напишите нам на", "pt": "Se o problema persistir, escreve-nos para"},
    "— rado ćemo pomoći.":{"en": "— we’ll gladly help.", "de": "— wir helfen gern.", "fr": "— nous t’aiderons volontiers.", "es": "— con gusto te ayudamos.", "it": "— saremo felici di aiutarti.", "ru": "— мы с радостью поможем.", "pt": "— teremos todo o gosto em ajudar."},
    "· zaokruži odgovor, pa proveri. Tvoj napredak se pamti na ovom uređaju.":{"en": "· circle the answer, then check. Your progress is saved on this device.", "de": "· Antwort einkreisen, dann prüfen. Dein Fortschritt wird auf diesem Gerät gespeichert.", "fr": "· entoure la réponse, puis vérifie. Ta progression est enregistrée sur cet appareil.", "es": "· rodea la respuesta y comprueba. Tu progreso se guarda en este dispositivo.", "it": "· cerchia la risposta, poi verifica. I tuoi progressi si salvano su questo dispositivo.", "ru": "· обведи ответ, затем проверь. Прогресс сохраняется на этом устройстве.", "pt": "· rodeia a resposta e confere. O teu progresso é guardado neste dispositivo."},
    "· izaberi tačan odgovor, pa proveri. Tvoj napredak se pamti na ovom uređaju.":{"en": "· choose the correct answer, then check. Your progress is saved on this device.", "de": "· wähle die richtige Antwort, dann prüfe. Dein Fortschritt wird auf diesem Gerät gespeichert.", "fr": "· choisis la bonne réponse, puis vérifie. Ta progression est enregistrée sur cet appareil.", "es": "· elige la respuesta correcta y comprueba. Tu progreso se guarda en este dispositivo.", "it": "· scegli la risposta giusta, poi verifica. I tuoi progressi si salvano su questo dispositivo.", "ru": "· выбери правильный ответ, затем проверь. Прогресс сохраняется на этом устройстве.", "pt": "· escolhe a resposta certa e confere. O teu progresso é guardado neste dispositivo."},
    "— uči s ljubavlju 💛":{"en": "— learn with love 💛", "de": "— lerne mit Liebe 💛", "fr": "— apprends avec amour 💛", "es": "— aprende con amor 💛", "it": "— impara con amore 💛", "ru": "— учись с любовью 💛", "pt": "— aprende com amor 💛"},
    "· bez kartice · otkaži kad želiš":{"en": "· no card · cancel anytime", "de": "· ohne Karte · jederzeit kündbar", "fr": "· sans carte · annule quand tu veux", "es": "· sin tarjeta · cancela cuando quieras", "it": "· senza carta · disdici quando vuoi", "ru": "· без карты · отмена в любой момент", "pt": "· sem cartão · cancela quando quiseres"},
    "uči s ljubavlju · mathia.rs":{"en": "learn with love · mathia.rs", "de": "lerne mit Liebe · mathia.rs", "fr": "apprends avec amour · mathia.rs", "es": "aprende con amor · mathia.rs", "it": "impara con amore · mathia.rs", "ru": "учись с любовью · mathia.rs", "pt": "aprende com amor · mathia.rs"},
    "© Mathia · uči s ljubavlju · mathia.rs":{"en": "© Mathia · learn with love · mathia.rs", "de": "© Mathia · lerne mit Liebe · mathia.rs", "fr": "© Mathia · apprends avec amour · mathia.rs", "es": "© Mathia · aprende con amor · mathia.rs", "it": "© Mathia · impara con amore · mathia.rs", "ru": "© Mathia · учись с любовью · mathia.rs", "pt": "© Mathia · aprende com amor · mathia.rs"},
    "Srednja škola · uči s ljubavlju · mathia.rs":{"en": "High school · learn with love · mathia.rs", "de": "Oberschule · lerne mit Liebe · mathia.rs", "fr": "Lycée · apprends avec amour · mathia.rs", "es": "Secundaria · aprende con amor · mathia.rs", "it": "Superiori · impara con amore · mathia.rs", "ru": "Средняя школа · учись с любовью · mathia.rs", "pt": "Secundário · aprende com amor · mathia.rs"},
    "Fakultet · uči s ljubavlju · mathia.rs":{"en": "University · learn with love · mathia.rs", "de": "Universität · lerne mit Liebe · mathia.rs", "fr": "Université · apprends avec amour · mathia.rs", "es": "Universidad · aprende con amor · mathia.rs", "it": "Università · impara con amore · mathia.rs", "ru": "Университет · учись с любовью · mathia.rs", "pt": "Universidade · aprende com amor · mathia.rs"},
    "MATHIA · Osnove · uči s ljubavlju · mathia.rs":{"en": "MATHIA · Basics · learn with love · mathia.rs", "de": "MATHIA · Grundlagen · lerne mit Liebe · mathia.rs", "fr": "MATHIA · Bases · apprends avec amour · mathia.rs", "es": "MATHIA · Básicos · aprende con amor · mathia.rs", "it": "MATHIA · Basi · impara con amore · mathia.rs", "ru": "MATHIA · Основы · учись с любовью · mathia.rs", "pt": "MATHIA · Básicos · aprende com amor · mathia.rs"},
    "Rešen primer":{"en": "Worked example", "de": "Gelöstes Beispiel", "fr": "Exemple résolu", "es": "Ejemplo resuelto", "it": "Esempio svolto", "ru": "Разобранный пример", "pt": "Exemplo resolvido"},
    "Ova skripta je deo Mathia pretplate. Molimo te da je ne deliš — pravljena je s puno pažnje baš za tebe.":{"en": "These notes are part of a Mathia subscription. Please don’t share them — they were made with great care just for you.", "de": "Dieses Skript ist Teil eines Mathia-Abos. Bitte teile es nicht — es wurde mit viel Sorgfalt für dich erstellt.", "fr": "Ce cours fait partie d’un abonnement Mathia. Merci de ne pas le partager — il a été fait avec soin, juste pour toi.", "es": "Estos apuntes son parte de una suscripción Mathia. No los compartas — se hicieron con mucho cuidado para ti.", "it": "Questa dispensa fa parte di un abbonamento Mathia. Non condividerla — è stata fatta con cura proprio per te.", "ru": "Этот конспект — часть подписки Mathia. Пожалуйста, не делись им — он сделан с заботой именно для тебя.", "pt": "Estes apontamentos fazem parte de uma subscrição Mathia. Não os partilhes — foram feitos com muito cuidado só para ti."},
    "Ovaj priručnik je deo Mathia pretplate. Molimo te da ga ne deliš — pravljen je baš za tebe.":{"en": "This handbook is part of a Mathia subscription. Please don’t share it — it was made just for you.", "de": "Dieses Handbuch ist Teil eines Mathia-Abos. Bitte teile es nicht — es wurde für dich erstellt.", "fr": "Ce manuel fait partie d’un abonnement Mathia. Merci de ne pas le partager — il a été fait pour toi.", "es": "Este manual es parte de una suscripción Mathia. No lo compartas — se hizo para ti.", "it": "Questo manuale fa parte di un abbonamento Mathia. Non condividerlo — è stato fatto per te.", "ru": "Этот справочник — часть подписки Mathia. Пожалуйста, не делись им — он сделан для тебя.", "pt": "Este manual faz parte de uma subscrição Mathia. Não o partilhes — foi feito para ti."},
    "Ovaj priručnik je deo Mathia pretplate. Molimo te da ga ne deliš — pravljen je s puno pažnje baš za tebe.":{"en": "This handbook is part of a Mathia subscription. Please don’t share it — it was made with great care just for you.", "de": "Dieses Handbuch ist Teil eines Mathia-Abos. Bitte teile es nicht — es wurde mit viel Sorgfalt für dich erstellt.", "fr": "Ce manuel fait partie d’un abonnement Mathia. Merci de ne pas le partager — il a été fait avec soin, juste pour toi.", "es": "Este manual es parte de una suscripción Mathia. No lo compartas — se hizo con mucho cuidado para ti.", "it": "Questo manuale fa parte di un abbonamento Mathia. Non condividerlo — è stato fatto con cura proprio per te.", "ru": "Этот справочник — часть подписки Mathia. Пожалуйста, не делись им — он сделан с заботой именно для тебя.", "pt": "Este manual faz parte de uma subscrição Mathia. Não o partilhes — foi feito com muito cuidado só para ti."},
    "skroluj naniže ↓":{"en": "scroll down ↓", "de": "nach unten scrollen ↓", "fr": "défile vers le bas ↓", "es": "desplázate hacia abajo ↓", "it": "scorri in giù ↓", "ru": "прокрути вниз ↓", "pt": "desliza para baixo ↓"},
    "Marina kaže":{"en": "Marina says", "de": "Marina sagt", "fr": "Marina dit", "es": "Marina dice", "it": "Marina dice", "ru": "Марина говорит", "pt": "A Marina diz"},
    "🧩 Vežbaj zadatke":{"en": "🧩 Practise problems", "de": "🧩 Aufgaben üben", "fr": "🧩 Entraîne-toi", "es": "🧩 Practica problemas", "it": "🧩 Esercitati", "ru": "🧩 Порешай задачи", "pt": "🧩 Pratica exercícios"},
    "Šta sve učimo":{"en": "What we learn", "de": "Was wir lernen", "fr": "Ce que nous apprenons", "es": "Qué aprendemos", "it": "Cosa impariamo", "ru": "Что мы учим", "pt": "O que aprendemos"},
    "Šta sve učimo ove godine":{"en": "What we learn this year", "de": "Was wir dieses Jahr lernen", "fr": "Ce que nous apprenons cette année", "es": "Qué aprendemos este año", "it": "Cosa impariamo quest’anno", "ru": "Что мы учим в этом году", "pt": "O que aprendemos este ano"},
    "Interaktivni zadaci sa proverom i rešenjem, po oblastima.":{"en": "Interactive problems with checking and solutions, by topic.", "de": "Interaktive Aufgaben mit Überprüfung und Lösung, nach Themen.", "fr": "Exercices interactifs avec vérification et corrigé, par thème.", "es": "Problemas interactivos con comprobación y solución, por temas.", "it": "Esercizi interattivi con verifica e soluzione, per argomento.", "ru": "Интерактивные задачи с проверкой и решением, по темам.", "pt": "Exercícios interativos com verificação e solução, por tema."},
    "Interaktivni zadaci sa proverom i objašnjenjem, po oblastima.":{"en": "Interactive problems with checking and explanation, by topic.", "de": "Interaktive Aufgaben mit Überprüfung und Erklärung, nach Themen.", "fr": "Exercices interactifs avec vérification et explication, par thème.", "es": "Problemas interactivos con comprobación y explicación, por temas.", "it": "Esercizi interattivi con verifica e spiegazione, per argomento.", "ru": "Интерактивные задачи с проверкой и объяснением, по темам.", "pt": "Exercícios interativos com verificação e explicação, por tema."},
    "Interaktivni zadaci o sintaksi i konceptima, sa proverom i objašnjenjem.":{"en": "Interactive problems on syntax and concepts, with checking and explanation.", "de": "Interaktive Aufgaben zu Syntax und Konzepten, mit Überprüfung und Erklärung.", "fr": "Exercices interactifs sur la syntaxe et les concepts, avec vérification et explication.", "es": "Problemas interactivos sobre sintaxis y conceptos, con comprobación y explicación.", "it": "Esercizi interattivi su sintassi e concetti, con verifica e spiegazione.", "ru": "Интерактивные задачи по синтаксису и концепциям, с проверкой и объяснением.", "pt": "Exercícios interativos sobre sintaxe e conceitos, com verificação e explicação."},
    "priručnik · programiranje":{"en": "handbook · programming", "de": "Handbuch · Programmierung", "fr": "manuel · programmation", "es": "manual · programación", "it": "manuale · programmazione", "ru": "справочник · программирование", "pt": "manual · programação"},
    "Programiranje · Vežba":{"en": "Programming · Practice", "de": "Programmierung · Übung", "fr": "Programmation · Exercices", "es": "Programación · Práctica", "it": "Programmazione · Esercizi", "ru": "Программирование · Практика", "pt": "Programação · Prática"},
    "Elektrotehnika · Vežba":{"en": "Electrical engineering · Practice", "de": "Elektrotechnik · Übung", "fr": "Génie électrique · Exercices", "es": "Electrotecnia · Práctica", "it": "Elettrotecnica · Esercizi", "ru": "Электротехника · Практика", "pt": "Eletrotecnia · Prática"},
    "Fakultet · Vežba":{"en": "University · Practice", "de": "Universität · Übung", "fr": "Université · Exercices", "es": "Universidad · Práctica", "it": "Università · Esercizi", "ru": "Университет · Практика", "pt": "Universidade · Prática"},
    "e-priručnik · formule":{"en": "e-handbook · formulas", "de": "E-Handbuch · Formeln", "fr": "e-manuel · formules", "es": "e-manual · fórmulas", "it": "e-manuale · formule", "ru": "э-справочник · формулы", "pt": "e-manual · fórmulas"},
    "priručnik formula · osnovna škola":{"en": "formula handbook · primary school", "de": "Formel-Handbuch · Grundschule", "fr": "manuel de formules · primaire", "es": "manual de fórmulas · primaria", "it": "manuale di formule · elementari", "ru": "справочник формул · начальная школа", "pt": "manual de fórmulas · ensino básico"},
    "skripta · osnovna škola":{"en": "notes · primary school", "de": "Skript · Grundschule", "fr": "cours · primaire", "es": "apuntes · primaria", "it": "dispensa · elementari", "ru": "конспект · начальная школа", "pt": "apontamentos · ensino básico"},
    "Sve ključne formule na jednom mestu — za brzo ponavljanje.":{"en": "All key formulas in one place — for quick revision.", "de": "Alle wichtigen Formeln an einem Ort — für schnelles Wiederholen.", "fr": "Toutes les formules clés au même endroit — pour réviser vite.", "es": "Todas las fórmulas clave en un lugar — para repasar rápido.", "it": "Tutte le formule chiave in un posto — per un ripasso veloce.", "ru": "Все ключевые формулы в одном месте — для быстрого повторения.", "pt": "Todas as fórmulas-chave num só lugar — para rever depressa."},
    "Najvažnije formule":{"en": "The most important formulas", "de": "Die wichtigsten Formeln", "fr": "Les formules essentielles", "es": "Las fórmulas más importantes", "it": "Le formule più importanti", "ru": "Самые важные формулы", "pt": "As fórmulas mais importantes"},
    "Teorija, ključne formule i primeri korak po korak.":{"en": "Theory, key formulas and step-by-step examples.", "de": "Theorie, wichtige Formeln und Schritt-für-Schritt-Beispiele.", "fr": "Théorie, formules clés et exemples pas à pas.", "es": "Teoría, fórmulas clave y ejemplos paso a paso.", "it": "Teoria, formule chiave ed esempi passo dopo passo.", "ru": "Теория, ключевые формулы и примеры шаг за шагом.", "pt": "Teoria, fórmulas-chave e exemplos passo a passo."},
    "Sledeći korak →":{"en": "Next step →", "de": "Nächster Schritt →", "fr": "Étape suivante →", "es": "Siguiente paso →", "it": "Prossimo passo →", "ru": "Следующий шаг →", "pt": "Próximo passo →"},
    "Kako se uči:":{"en": "How to study:", "de": "So lernst du:", "fr": "Comment étudier :", "es": "Cómo estudiar:", "it": "Come studiare:", "ru": "Как учиться:", "pt": "Como estudar:"},
    "svaka oblast ima kratku teoriju, karticu sa ključnim formulama i primer koji se rešava":{"en": "each topic has short theory, a key-formula card and an example that gets solved", "de": "jedes Thema hat kurze Theorie, eine Formelkarte und ein gelöstes Beispiel", "fr": "chaque thème a une théorie courte, une fiche de formules et un exemple résolu", "es": "cada tema tiene teoría breve, una tarjeta de fórmulas y un ejemplo resuelto", "it": "ogni argomento ha teoria breve, una scheda di formule e un esempio svolto", "ru": "в каждой теме краткая теория, карточка формул и разобранный пример", "pt": "cada tema tem teoria breve, um cartão de fórmulas e um exemplo resolvido"},
    ". Probaj sam, pa otkrij rešenje. 💪":{"en": ". Try it yourself, then reveal the solution. 💪", "de": ". Versuch es selbst, dann zeig die Lösung. 💪", "fr": ". Essaie toi-même, puis découvre la solution. 💪", "es": ". Inténtalo tú, luego revela la solución. 💪", "it": ". Provaci da solo, poi scopri la soluzione. 💪", "ru": ". Попробуй сам, потом открой решение. 💪", "pt": ". Tenta sozinho e depois revela a solução. 💪"},
    "Sledeći korak: zbirka rešenih zadataka i probni testovi — uz svoju profesoricu.":{"en": "Next step: a collection of solved problems and practice tests — with your teacher.", "de": "Nächster Schritt: gelöste Aufgaben und Übungstests — mit deiner Lehrerin.", "fr": "Étape suivante : recueil d’exercices corrigés et tests blancs — avec ta professeure.", "es": "Siguiente paso: colección de problemas resueltos y tests de práctica — con tu profesora.", "it": "Prossimo passo: raccolta di esercizi svolti e test di prova — con la tua insegnante.", "ru": "Следующий шаг: сборник решённых задач и пробные тесты — с твоей преподавательницей.", "pt": "Próximo passo: coletânea de exercícios resolvidos e testes — com a tua professora."},
    "← Mathia · Početna":{"en": "← Mathia · Home", "de": "← Mathia · Start", "fr": "← Mathia · Accueil", "es": "← Mathia · Inicio", "it": "← Mathia · Home", "ru": "← Mathia · Главная", "pt": "← Mathia · Início"},
    "Kvadratna jednačina":{"en": "Quadratic equation", "de": "Quadratische Gleichung", "fr": "Équation du second degré", "es": "Ecuación cuadrática", "it": "Equazione di secondo grado", "ru": "Квадратное уравнение", "pt": "Equação do segundo grau"}
  };
  function lng(){try{var s=localStorage.getItem('mathia_lang');if(s)return s.slice(0,2).toLowerCase();}catch(e){}return (document.documentElement.lang||'sr').slice(0,2).toLowerCase();}
  var nodes=[];
  function collect(){
    nodes=[];
    var w=document.createTreeWalker(document.body,NodeFilter.SHOW_TEXT,null,false),n;
    while(n=w.nextNode()){
      var p=n.parentNode; if(!p)continue; var tg=p.nodeName; if(tg==='SCRIPT'||tg==='STYLE'||tg==='TEXTAREA')continue;
      var key=(n.nodeValue||'').trim(); if(key.length<2)continue;
      if(D[key]){ if(n.__o===undefined)n.__o=n.nodeValue; nodes.push([n,D[key],key]); }
    }
  }
  function ap(){var l=lng();nodes.forEach(function(p){var n=p[0],m=p[1];var v=(l==='sr'||!m[l])?n.__o:n.__o.replace(p[2],m[l]);n.nodeValue=v;});}
  function run(){collect();ap();}
  if(document.readyState==='loading')addEventListener('DOMContentLoaded',run);else run();
  addEventListener('storage',function(e){if(e.key==='mathia_lang')ap();});
  window.addEventListener('mathia:lang',ap);
  try{new MutationObserver(function(){ap();}).observe(document.documentElement,{attributes:true,attributeFilter:['lang']});}catch(e){}
})();
