// Rekonstruisano iz UZORAK Skripte. Oblik kao ma1.js. Srpski je ključ za prevode.
const r = String.raw;
const skripta = [
{ n:1, title:{sr:"Kompleksni brojevi i kompleksna ravan"},
  lead:[{sr:"Kompleksan broj"}," ",{m:"z=a+bi"}," ",{sr:"predstavlja se tačkom u Gausovoj ravni. Pored algebarskog, koristi se trigonometrijski i Ojlerov oblik, određen modulom"}," ",{m:"r"}," ",{sr:"i argumentom"}," ",{m:"\\varphi"},"."],
  zapamti:[
    {label:{sr:"Algebarski oblik i konjugat"}, tex:"z=a+bi,\\qquad \\overline{z}=a-bi"},
    {label:{sr:"Moduo i argument"}, tex:"|z|=\\sqrt{a^2+b^2},\\qquad \\tan\\varphi=\\frac{b}{a}"},
    {label:{sr:"Ojlerov oblik"}, tex:"z=r\\,e^{\\,i\\varphi}"},
    {label:{sr:"Moavrova formula"}, tex:"z^n=r^n\\big(\\cos n\\varphi+i\\sin n\\varphi\\big)"},
  ],
  primer:{ task:[{sr:"Napisati"}," ",{m:"z=-1+i"}," ",{sr:"u Ojlerovom obliku."}],
    steps:[
      [{sr:"Moduo:"}," ",{m:"r=\\sqrt{(-1)^2+1^2}=\\sqrt2"},"."],
      [{sr:"Tačka je u drugom kvadrantu, pa"}," ",{m:"\\varphi=\\dfrac{3\\pi}{4}"},"."],
      [{m:"z=\\sqrt2\\,e^{\\,i\\,3\\pi/4}"},"."],
    ]} },
{ n:2, title:{sr:"Kompleksne funkcije i preslikavanja"},
  lead:[{sr:"Kompleksna funkcija"}," ",{m:"w=f(z)"}," ",{sr:"preslikava jednu ravan u drugu i razlaže se na realni i imaginarni deo"}," ",{m:"u(x,y)"}," ",{sr:"i"}," ",{m:"v(x,y)"},"."],
  zapamti:[
    {label:{sr:"Razlaganje funkcije"}, tex:"f(z)=u(x,y)+i\\,v(x,y)"},
    {label:{sr:"Kvadratno preslikavanje"}, tex:"w=z^2\\ \\Rightarrow\\ u=x^2-y^2,\\ \\ v=2xy"},
  ],
  primer:{ task:[{sr:"Za"}," ",{m:"f(z)=z^2"}," ",{sr:"odrediti"}," ",{m:"u"}," ",{sr:"i"}," ",{m:"v"},"."],
    steps:[
      [{m:"z^2=(x+iy)^2=x^2-y^2+i\\,2xy"},"."],
      [{sr:"Realni deo:"}," ",{m:"u=x^2-y^2"},"."],
      [{sr:"Imaginarni deo:"}," ",{m:"v=2xy"},"."],
    ]} },
{ n:3, title:{sr:"Granična vrednost i neprekidnost"},
  lead:[{sr:"Granična vrednost"}," ",{m:"\\lim_{z\\to z_0}f(z)"}," ",{sr:"mora biti ista bez obzira na pravac prilaza tački"}," ",{m:"z_0"},{sr:". Funkcija je neprekidna kada se granična vrednost poklapa sa vrednošću funkcije."}],
  zapamti:[
    {label:{sr:"Granična vrednost"}, tex:"\\lim_{z\\to z_0} f(z)=L"},
    {label:{sr:"Neprekidnost"}, tex:"\\lim_{z\\to z_0} f(z)=f(z_0)"},
  ],
  primer:{ task:[{sr:"Izračunati"}," ",{m:"\\displaystyle\\lim_{z\\to i}\\,(z^2+1)"},"."],
    steps:[
      [{sr:"Uvrstimo"}," ",{m:"z=i"},":"," ",{m:"i^2+1"},"."],
      [{m:"i^2=-1"},{sr:", pa je"}," ",{m:"-1+1"},"."],
      [{sr:"Granična vrednost je"}," ",{m:"0"},"."],
    ]} },
{ n:4, title:{sr:"Izvod i analitičke funkcije"},
  lead:[{sr:"Funkcija je analitička (holomorfna) u oblasti ako je u svakoj tački kompleksno diferencijabilna. To je ekvivalentno Koši–Rimanovim uslovima; tada su"}," ",{m:"u"}," ",{sr:"i"}," ",{m:"v"}," ",{sr:"harmonijske funkcije."}],
  zapamti:[
    {label:{sr:"Definicija izvoda"}, tex:"f'(z)=\\lim_{\\Delta z\\to0}\\frac{f(z+\\Delta z)-f(z)}{\\Delta z}"},
    {label:{sr:"Koši–Rimanovi uslovi"}, tex:"u_x=v_y,\\qquad u_y=-v_x"},
    {label:{sr:"Harmonijnost"}, tex:"u_{xx}+u_{yy}=0"},
  ],
  primer:{ task:[{sr:"Pokazati da je"}," ",{m:"f(z)=z^2"}," ",{sr:"analitička i naći"}," ",{m:"f'(z)"},"."],
    steps:[
      [{m:"u=x^2-y^2,\\ v=2xy"},"."],
      [{m:"u_x=2x=v_y"}," ",{sr:"i"}," ",{m:"u_y=-2y=-v_x"}," ",{sr:"— uslovi važe."}],
      [{sr:"Funkcija je analitička, a izvod je"}," ",{m:"f'(z)=2z"},"."],
    ]} },
{ n:5, title:{sr:"Elementarne kompleksne funkcije"},
  lead:[{sr:"Eksponencijalna, trigonometrijske i logaritamska funkcija proširuju se na kompleksnu ravan. Logaritam je višeznačan jer je argument određen do na"}," ",{m:"2k\\pi"},"."],
  zapamti:[
    {label:{sr:"Eksponencijalna funkcija"}, tex:"e^{z}=e^{x}(\\cos y+i\\sin y)"},
    {label:{sr:"Sinus preko eksponencijalne"}, tex:"\\sin z=\\frac{e^{iz}-e^{-iz}}{2i}"},
    {label:{sr:"Kosinus preko eksponencijalne"}, tex:"\\cos z=\\frac{e^{iz}+e^{-iz}}{2}"},
    {label:{sr:"Logaritam (višeznačan)"}, tex:"\\ln z=\\ln|z|+i\\,(\\arg z+2k\\pi)"},
  ],
  primer:{ task:[{sr:"Izračunati glavnu vrednost"}," ",{m:"\\ln i"},"."],
    steps:[
      [{m:"|i|=1"},{sr:", pa"}," ",{m:"\\ln|i|=0"},"."],
      [{m:"\\arg i=\\dfrac{\\pi}{2}"},"."],
      [{sr:"Glavna vrednost:"}," ",{m:"\\ln i=i\\dfrac{\\pi}{2}"},"."],
    ]} },
{ n:6, title:{sr:"Kompleksni integral"},
  lead:[{sr:"Kompleksni integral"}," ",{m:"\\int\\limits_C f(z)\\,dz"}," ",{sr:"računa se parametrizacijom krive. Korisna je ML ocena za gornju granicu modula integrala."}],
  zapamti:[
    {label:{sr:"Definicija"}, tex:"\\int\\limits_C f(z)\\,dz=\\int_a^b f\\big(z(t)\\big)\\,z'(t)\\,dt"},
    {label:{sr:"ML ocena"}, tex:"\\left|\\int\\limits_C f(z)\\,dz\\right|\\le M\\cdot L"},
  ],
  primer:{ task:[{sr:"Izračunati"}," ",{m:"\\displaystyle\\oint\\limits_C \\frac{dz}{z}"}," ",{sr:"po jediničnom krugu."}],
    steps:[
      [{sr:"Parametrizacija:"}," ",{m:"z=e^{it},\\ t\\in[0,2\\pi]"},{sr:", pa"}," ",{m:"z'=i\\,e^{it}"},"."],
      [{m:"\\displaystyle\\oint\\limits_C\\frac{dz}{z}=\\int_0^{2\\pi}\\frac{i\\,e^{it}}{e^{it}}\\,dt=\\int_0^{2\\pi} i\\,dt"},"."],
      [{m:"=2\\pi i"},"."],
    ]} },
{ n:7, title:{sr:"Košijeva integralna teorema i formule"},
  lead:[{sr:"Za funkciju analitičku u prosto povezanoj oblasti integral po zatvorenoj konturi je nula (Košijeva teorema). Integralna formula daje vrednost funkcije i njenih izvoda preko konturnog integrala."}],
  zapamti:[
    {label:{sr:"Košijeva integralna teorema"}, tex:"\\oint\\limits_C f(z)\\,dz=0"},
    {label:{sr:"Košijeva integralna formula"}, tex:"f(z_0)=\\frac{1}{2\\pi i}\\oint\\limits_C\\frac{f(z)}{z-z_0}\\,dz"},
    {label:{sr:"Formula za izvode"}, tex:"f^{(n)}(z_0)=\\frac{n!}{2\\pi i}\\oint\\limits_C\\frac{f(z)}{(z-z_0)^{n+1}}\\,dz"},
  ],
  primer:{ task:[{sr:"Izračunati"}," ",{m:"\\displaystyle\\oint\\limits_C\\frac{z^2}{z-1}\\,dz"}," ",{sr:"po konturi oko"}," ",{m:"z=1"},"."],
    steps:[
      [{sr:"Po integralnoj formuli"}," ",{m:"f(z)=z^2"},","," ",{m:"z_0=1"},"."],
      [{m:"f(1)=1"},"."],
      [{m:"\\displaystyle\\oint\\limits_C\\frac{z^2}{z-1}\\,dz=2\\pi i\\cdot f(1)=2\\pi i"},"."],
    ]} },
{ n:8, title:{sr:"Tejlorov i Loranov red"},
  lead:[{sr:"Analitička funkcija razvija se u Tejlorov red u krugu, a u prstenu oko singulariteta u Loranov red, koji sadrži i negativne stepene."}],
  zapamti:[
    {label:{sr:"Tejlorov red"}, tex:"f(z)=\\sum_{n=0}^{\\infty}\\frac{f^{(n)}(z_0)}{n!}\\,(z-z_0)^n"},
    {label:{sr:"Loranov red"}, tex:"f(z)=\\sum_{n=-\\infty}^{\\infty} c_n\\,(z-z_0)^n"},
    {label:{sr:"Koeficijent Loranovog reda"}, tex:"c_n=\\frac{1}{2\\pi i}\\oint\\limits_C\\frac{f(z)}{(z-z_0)^{n+1}}\\,dz"},
  ],
  primer:{ task:[{sr:"Razviti"}," ",{m:"e^{z}"}," ",{sr:"u Tejlorov red oko"}," ",{m:"z_0=0"},"."],
    steps:[
      [{sr:"Svi izvodi su"}," ",{m:"e^{z}"},{sr:", a u nuli vrede"}," ",{m:"1"},"."],
      [{sr:"Koeficijenti su"}," ",{m:"\\dfrac{1}{n!}"},"."],
      [{m:"e^{z}=\\displaystyle\\sum_{n=0}^{\\infty}\\frac{z^n}{n!}"},"."],
    ]} },
{ n:9, title:{sr:"Singulariteti i reziduumi"},
  lead:[{sr:"Izolovani singulariteti dele se na otklonjive, polove i esencijalne. Reziduum je koeficijent uz"}," ",{m:"(z-z_0)^{-1}"}," ",{sr:"u Loranovom redu i ključan je za teoremu o reziduumima."}],
  zapamti:[
    {label:{sr:"Reziduum u prostom polu"}, tex:"\\operatorname{Res}_{z_0}f=\\lim_{z\\to z_0}(z-z_0)\\,f(z)"},
    {label:{sr:"Reziduum u polu reda m"}, tex:"\\operatorname{Res}_{z_0}f=\\frac{1}{(m-1)!}\\lim_{z\\to z_0}\\frac{d^{\\,m-1}}{dz^{\\,m-1}}\\Big[(z-z_0)^m f\\Big]"},
    {label:{sr:"Teorema o reziduumima"}, tex:"\\oint\\limits_C f(z)\\,dz=2\\pi i\\sum\\operatorname{Res}f"},
  ],
  primer:{ task:[{sr:"Naći"}," ",{m:"\\operatorname{Res}_{z=1}\\dfrac{z}{(z-1)(z+2)}"},"."],
    steps:[
      [{sr:"Prost pol u"}," ",{m:"z=1"},"."],
      [{m:"\\operatorname{Res}=\\lim_{z\\to1}\\dfrac{z}{z+2}=\\dfrac{1}{3}"},"."],
      [{sr:"Dakle reziduum je"}," ",{m:"\\dfrac{1}{3}"},"."],
    ]} },
{ n:10, title:{sr:"Primena reziduuma na realne integrale"},
  lead:[{sr:"Teorema o reziduumima moćno je oruđe za realne integrale: trigonometrijske integrale ("},{m:"z=e^{i\\theta}"},{sr:") i integrale po celoj realnoj osi (zatvaranjem konture u gornjoj poluravni)."}],
  zapamti:[
    {label:{sr:"Trigonometrijski tip"}, tex:"z=e^{i\\theta},\\qquad d\\theta=\\frac{dz}{i\\,z}"},
    {label:{sr:"Integral po realnoj osi"}, tex:"\\int_{-\\infty}^{\\infty} f\\,dx=2\\pi i\\sum\\operatorname{Res}_{\\text{gornja poluravan}}"},
  ],
  primer:{ task:[{sr:"Izračunati"}," ",{m:"\\displaystyle\\int_{-\\infty}^{\\infty}\\frac{dx}{x^2+1}"},"."],
    steps:[
      [{sr:"Pol u gornjoj poluravni je"}," ",{m:"z=i"},"."],
      [{m:"\\operatorname{Res}_{i}\\dfrac{1}{z^2+1}=\\dfrac{1}{2i}"},"."],
      [{sr:"Integral"}," ",{m:"=2\\pi i\\cdot\\dfrac{1}{2i}=\\pi"},"."],
    ]} },
{ n:11, title:{sr:"Konformna preslikavanja"},
  lead:[{sr:"Konformno preslikavanje čuva uglove; svaka analitička funkcija sa"}," ",{m:"f'(z)\\neq0"}," ",{sr:"je konformna. Mebijusova transformacija preslikava krugove i prave u krugove i prave."}],
  zapamti:[
    {label:{sr:"Uslov konformnosti"}, tex:"f\\ \\text{analitička},\\ f'(z)\\neq0"},
    {label:{sr:"Mebijusova transformacija"}, tex:"w=\\frac{az+b}{cz+d},\\qquad ad-bc\\neq0"},
  ],
  primer:{ task:[{sr:"Da li je"}," ",{m:"f(z)=\\dfrac{1}{z}"}," ",{sr:"konformno u tački"}," ",{m:"z=1"},"?"],
    steps:[
      [{sr:"Izvod:"}," ",{m:"f'(z)=-\\dfrac{1}{z^2}"},"."],
      [{m:"f'(1)=-1\\neq0"},"."],
      [{sr:"Jeste konformno u"}," ",{m:"z=1"},"."],
    ]} },
];
module.exports = { skripta };
