// Rekonstruisano iz UZORAK Skripte. Oblik kao ma1.js. Srpski je ključ za prevode.
const r = String.raw;
const skripta = [
{ n:1, title:{sr:"Brojni redovi"},
  lead:[{sr:"Brojni red"}," ",{m:"\\sum a_n"}," ",{sr:"konvergira ako niz parcijalnih suma ima konačnu graničnu vrednost. Konvergenciju ispitujemo poredbenim, Dalamberovim (količnik) i Košijevim (koren) kriterijumom, a alternativne redove Lajbnicovim kriterijumom."}],
  zapamti:[
    {label:{sr:"Suma reda"}, tex:"\\sum_{n=1}^{\\infty} a_n=\\lim_{N\\to\\infty}\\sum_{n=1}^{N} a_n"},
    {label:{sr:"Potreban uslov konvergencije"}, tex:"\\sum a_n\\ \\text{konvergira}\\ \\Rightarrow\\ a_n\\to0"},
    {label:{sr:"Geometrijski red"}, tex:"\\sum_{n=0}^{\\infty} q^{\\,n}=\\frac{1}{1-q},\\qquad |q|<1"},
    {label:{sr:"Dalamberov kriterijum (količnik)"}, tex:"\\lim_{n\\to\\infty}\\left|\\frac{a_{n+1}}{a_n}\\right|=L \\quad L<1\\ \\Rightarrow\\ \\text{konvergira}"},
    {label:{sr:"Košijev kriterijum (koren)"}, tex:"\\lim_{n\\to\\infty}\\sqrt[n]{|a_n|}=L \\quad L<1\\ \\Rightarrow\\ \\text{konvergira}"},
  ],
  primer:{ task:[{sr:"Izračunati sumu reda"}," ",{m:"\\displaystyle\\sum_{n=1}^{\\infty}\\frac{1}{2^{n}}"},"."],
    steps:[
      [{sr:"Geometrijski red sa prvim članom"}," ",{m:"a_1=\\tfrac12"}," ",{sr:"i količnikom"}," ",{m:"q=\\tfrac12"},"."],
      [{sr:"Suma:"}," ",{m:"S=\\dfrac{a_1}{1-q}=\\dfrac{1/2}{1-1/2}"},"."],
      [{m:"S=\\dfrac{1/2}{1/2}=1"},"."],
    ]} },
{ n:2, title:{sr:"Funkcionalni i stepeni redovi"},
  lead:[{sr:"Stepeni red"}," ",{m:"\\sum a_n(x-x_0)^n"}," ",{sr:"konvergira unutar intervala određenog poluprečnikom konvergencije"}," ",{m:"R"},{sr:". Mnoge funkcije razvijamo u stepeni (Tejlorov, Maklorenov) red."}],
  zapamti:[
    {label:{sr:"Stepeni red"}, tex:"\\sum_{n=0}^{\\infty} a_n\\,(x-x_0)^n"},
    {label:{sr:"Poluprečnik konvergencije"}, tex:"R=\\lim_{n\\to\\infty}\\left|\\frac{a_n}{a_{n+1}}\\right|"},
    {label:{sr:"Razvoj eksponencijalne funkcije"}, tex:"e^{x}=\\sum_{n=0}^{\\infty}\\frac{x^{n}}{n!}"},
    {label:{sr:"Razvoj sinusa"}, tex:"\\sin x=\\sum_{n=0}^{\\infty}\\frac{(-1)^n x^{2n+1}}{(2n+1)!}"},
  ],
  primer:{ task:[{sr:"Naći poluprečnik konvergencije reda"}," ",{m:"\\displaystyle\\sum_{n=1}^{\\infty}\\frac{x^{n}}{n}"},"."],
    steps:[
      [{sr:"Koeficijent je"}," ",{m:"a_n=\\dfrac1n"},"."],
      [{m:"\\left|\\dfrac{a_n}{a_{n+1}}\\right|=\\dfrac{n+1}{n}\\to1"},"."],
      [{sr:"Poluprečnik konvergencije je"}," ",{m:"R=1"},"."],
    ]} },
{ n:3, title:{sr:"Krivolinijski integrali"},
  lead:[{sr:"Krivolinijski integral I vrste računa se po dužini luka, a II vrste po koordinatama. Ako je"}," ",{m:"P\\,dx+Q\\,dy"}," ",{sr:"totalni diferencijal, integral ne zavisi od putanje."}],
  zapamti:[
    {label:{sr:"Integral I vrste (po dužini luka)"}, tex:"\\int\\limits_C f\\,ds= \\quad \\int_a^b f\\big(x(t),y(t)\\big)\\sqrt{x'^2+y'^2}\\,dt"},
    {label:{sr:"Integral II vrste (po koordinatama)"}, tex:"\\int\\limits_C P\\,dx+Q\\,dy= \\quad \\int_a^b\\big(P\\,x'+Q\\,y'\\big)\\,dt"},
    {label:{sr:"Nezavisnost od putanje"}, tex:"\\frac{\\partial P}{\\partial y}=\\frac{\\partial Q}{\\partial x}"},
  ],
  primer:{ task:[{sr:"Izračunati"}," ",{m:"\\displaystyle\\int\\limits_C x\\,dx+y\\,dy"}," ",{sr:"od"}," ",{m:"(0,0)"}," ",{sr:"do"}," ",{m:"(1,1)"}," ",{sr:"duž prave"}," ",{m:"y=x"},"."],
    steps:[
      [{sr:"Pošto"}," ",{m:"\\dfrac{\\partial P}{\\partial y}=0=\\dfrac{\\partial Q}{\\partial x}"},{sr:", integral ne zavisi od putanje (potencijal"}," ",{m:"\\varphi=\\tfrac{x^2+y^2}{2}"},")."],
      [{sr:"Vrednost je razlika potencijala:"}," ",{m:"\\varphi(1,1)-\\varphi(0,0)"},"."],
      [{m:"=\\dfrac{1+1}{2}-0=1"},"."],
    ]} },
{ n:4, title:{sr:"Dvostruki integral"},
  lead:[{sr:"Dvostruki integral"}," ",{m:"\\iint\\limits_D f\\,dA"}," ",{sr:"računa se uzastopnim integraljenjem (Fubinijeva teorema). Kod kružnih oblasti koriste se polarne koordinate, a opštije smena promenljivih sa Jakobijanom."}],
  zapamti:[
    {label:{sr:"Dvostruki integral"}, tex:"\\iint\\limits_D f(x,y)\\,dA=\\int\\!\\!\\int f(x,y)\\,dy\\,dx"},
    {label:{sr:"Polarne koordinate"}, tex:"x=r\\cos\\varphi,\\ \\ y=r\\sin\\varphi,\\ \\ dA=r\\,dr\\,d\\varphi"},
    {label:{sr:"Površina oblasti"}, tex:"P=\\iint\\limits_D dA"},
  ],
  primer:{ task:[{sr:"Izračunati površinu kruga"}," ",{m:"x^2+y^2\\le R^2"}," ",{sr:"dvostrukim integralom."}],
    steps:[
      [{sr:"U polarnim koordinatama:"}," ",{m:"\\displaystyle P=\\int_0^{2\\pi}\\!\\!\\int_0^{R} r\\,dr\\,d\\varphi"},"."],
      [{sr:"Unutrašnji integral:"}," ",{m:"\\displaystyle\\int_0^{R} r\\,dr=\\dfrac{R^2}{2}"},"."],
      [{m:"\\displaystyle P=\\dfrac{R^2}{2}\\int_0^{2\\pi} d\\varphi=\\dfrac{R^2}{2}\\cdot 2\\pi=\\pi R^2"},"."],
    ]} },
{ n:5, title:{sr:"Trostruki integral"},
  lead:[{sr:"Trostruki integral"}," ",{m:"\\iiint\\limits_V f\\,dV"}," ",{sr:"računa se uzastopno, a kod tela sa simetrijom koriste se cilindrične ili sferne koordinate."}],
  zapamti:[
    {label:{sr:"Trostruki integral"}, tex:"\\iiint\\limits_V f(x,y,z)\\,dV"},
    {label:{sr:"Cilindrične koordinate"}, tex:"x=r\\cos\\varphi,\\ \\ y=r\\sin\\varphi,\\ \\ z=z \\quad dV=r\\,dr\\,d\\varphi\\,dz"},
    {label:{sr:"Sferne koordinate"}, tex:"x=\\rho\\sin\\theta\\cos\\varphi \\quad y=\\rho\\sin\\theta\\sin\\varphi,\\quad z=\\rho\\cos\\theta \\quad dV=\\rho^2\\sin\\theta\\,d\\rho\\,d\\theta\\,d\\varphi"},
  ],
  primer:{ task:[{sr:"Izračunati zapreminu lopte poluprečnika"}," ",{m:"R"}," ",{sr:"u sfernim koordinatama."}],
    steps:[
      [{m:"\\displaystyle V=\\int_0^{2\\pi}\\!\\!\\int_0^{\\pi}\\!\\!\\int_0^{R}\\rho^2\\sin\\theta\\,d\\rho\\,d\\theta\\,d\\varphi"},"."],
      [{sr:"Po faktorima:"}," ",{m:"\\displaystyle\\int_0^{R}\\rho^2 d\\rho=\\dfrac{R^3}{3}"},","," ",{m:"\\ \\int_0^{\\pi}\\sin\\theta\\,d\\theta=2"},","," ",{m:"\\ \\int_0^{2\\pi}d\\varphi=2\\pi"},"."],
      [{m:"V=\\dfrac{R^3}{3}\\cdot2\\cdot2\\pi=\\dfrac{4}{3}\\pi R^3"},"."],
    ]} },
{ n:6, title:{sr:"Površinski integrali"},
  lead:[{sr:"Površinski integral I vrste"}," ",{m:"\\iint\\limits_S f\\,dS"}," ",{sr:"sabira vrednosti po površi, a II vrste meri fluks vektorskog polja kroz orijentisanu površ."}],
  zapamti:[
    {label:{sr:"Integral I vrste"}, tex:"\\iint\\limits_S f\\,dS"},
    {label:{sr:"Fluks (integral II vrste)"}, tex:"\\iint\\limits_S \\vec F\\cdot\\vec n\\,dS"},
    {label:{sr:"Element površi (za z = g(x,y))"}, tex:"dS=\\sqrt{1+g_x^{\\,2}+g_y^{\\,2}}\\,dx\\,dy"},
  ],
  primer:{ task:[{sr:"Izračunati površinu dela ravni"}," ",{m:"z=x+y"}," ",{sr:"nad kvadratom"}," ",{m:"[0,1]\\times[0,1]"},"."],
    steps:[
      [{sr:"Parcijalni izvodi:"}," ",{m:"g_x=1,\\ g_y=1"},"."],
      [{sr:"Element površi:"}," ",{m:"dS=\\sqrt{1+1+1}\\,dx\\,dy=\\sqrt3\\,dx\\,dy"},"."],
      [{m:"\\displaystyle S=\\iint_{[0,1]^2}\\sqrt3\\,dx\\,dy=\\sqrt3"},"."],
    ]} },
{ n:7, title:{sr:"Integralne formule: Grin, Gaus, Stoks"},
  lead:[{sr:"Tri velike teoreme povezuju integrale različitih dimenzija: Grinova (ravan), Gaus–Ostrogradskijeva (zapremina i fluks) i Stoksova (cirkulacija i površ)."}],
  zapamti:[
    {label:{sr:"Grinova formula"}, tex:"\\oint\\limits_C P\\,dx+Q\\,dy= \\quad \\iint\\limits_D\\left(\\frac{\\partial Q}{\\partial x}-\\frac{\\partial P}{\\partial y}\\right)dA"},
    {label:{sr:"Gaus–Ostrogradskijeva formula"}, tex:"\\iint\\limits_S \\vec F\\cdot\\vec n\\,dS=\\iiint\\limits_V \\operatorname{div}\\vec F\\,dV"},
    {label:{sr:"Stoksova formula"}, tex:"\\oint\\limits_C \\vec F\\cdot d\\vec r=\\iint\\limits_S \\operatorname{rot}\\vec F\\cdot\\vec n\\,dS"},
  ],
  primer:{ task:[{sr:"Grinovom formulom izračunati"}," ",{m:"\\displaystyle\\oint\\limits_C -y\\,dx+x\\,dy"}," ",{sr:"po granici jediničnog kruga."}],
    steps:[
      [{sr:"Ovde je"}," ",{m:"P=-y,\\ Q=x"},{sr:", pa"}," ",{m:"\\dfrac{\\partial Q}{\\partial x}-\\dfrac{\\partial P}{\\partial y}=1-(-1)=2"},"."],
      [{m:"\\displaystyle\\oint\\limits_C -y\\,dx+x\\,dy=\\iint\\limits_D 2\\,dA=2\\cdot P(D)"},"."],
      [{sr:"Za jedinični krug"}," ",{m:"P(D)=\\pi"},{sr:", pa je rezultat"}," ",{m:"2\\pi"},"."],
    ]} },
{ n:8, title:{sr:"Vektorska analiza"},
  lead:[{sr:"Vektorska analiza proučava skalarna i vektorska polja pomoću operatora gradijent, divergencija i rotor, koji se kratko pišu preko operatora nabla"}," ",{m:"\\nabla"},"."],
  zapamti:[
    {label:{sr:"Gradijent"}, tex:"\\operatorname{grad}f=\\nabla f=\\Big(\\tfrac{\\partial f}{\\partial x},\\tfrac{\\partial f}{\\partial y},\\tfrac{\\partial f}{\\partial z}\\Big)"},
    {label:{sr:"Divergencija"}, tex:"\\operatorname{div}\\vec F=\\frac{\\partial P}{\\partial x}+\\frac{\\partial Q}{\\partial y}+\\frac{\\partial R}{\\partial z}"},
    {label:{sr:"Rotor"}, tex:"\\operatorname{rot}\\vec F=\\nabla\\times\\vec F"},
    {label:{sr:"Potencijalno polje"}, tex:"\\operatorname{rot}\\vec F=\\vec 0\\ \\Rightarrow\\ \\vec F=\\nabla\\varphi"},
  ],
  primer:{ task:[{sr:"Naći divergenciju polja"}," ",{m:"\\vec F=(x,\\,y,\\,z)"},"."],
    steps:[
      [{m:"P=x,\\ Q=y,\\ R=z"},"."],
      [{m:"\\operatorname{div}\\vec F=1+1+1"},"."],
      [{m:"\\operatorname{div}\\vec F=3"},"."],
    ]} },
{ n:9, title:{sr:"Kompleksni brojevi i funkcije"},
  lead:[{sr:"Kompleksna funkcija"}," ",{m:"w=f(z)"}," ",{sr:"razlaže se na realni i imaginarni deo. Elementarne funkcije (eksponencijalna, trigonometrijske, logaritam) proširuju se na kompleksnu ravan preko Ojlerove formule."}],
  zapamti:[
    {label:{sr:"Kompleksna funkcija"}, tex:"f(z)=u(x,y)+i\\,v(x,y)"},
    {label:{sr:"Eksponencijalna funkcija"}, tex:"e^{z}=e^{x}(\\cos y+i\\sin y)"},
    {label:{sr:"Ojlerova formula"}, tex:"e^{\\,i y}=\\cos y+i\\sin y"},
  ],
  primer:{ task:[{sr:"Izračunati"}," ",{m:"e^{\\,i\\pi}"},"."],
    steps:[
      [{sr:"Po Ojlerovoj formuli:"}," ",{m:"e^{\\,i\\pi}=\\cos\\pi+i\\sin\\pi"},"."],
      [{m:"\\cos\\pi=-1,\\ \\sin\\pi=0"},"."],
      [{m:"e^{\\,i\\pi}=-1"}," ",{sr:"(Ojlerov identitet"}," ",{m:"e^{\\,i\\pi}+1=0"},")."],
    ]} },
{ n:10, title:{sr:"Analitičke funkcije, Košijeva teorema i formule"},
  lead:[{sr:"Funkcija je analitička (holomorfna) ako je kompleksno diferencijabilna; to je ekvivalentno Koši–Rimanovim uslovima. Za analitičke funkcije važe Košijeva integralna teorema i integralna formula."}],
  zapamti:[
    {label:{sr:"Koši–Rimanovi uslovi"}, tex:"u_x=v_y,\\qquad u_y=-v_x"},
    {label:{sr:"Košijeva integralna teorema"}, tex:"\\oint\\limits_C f(z)\\,dz=0"},
    {label:{sr:"Košijeva integralna formula"}, tex:"f(z_0)=\\frac{1}{2\\pi i}\\oint\\limits_C\\frac{f(z)}{z-z_0}\\,dz"},
  ],
  primer:{ task:[{sr:"Proveriti Koši–Rimanove uslove za"}," ",{m:"f(z)=z^2"},"."],
    steps:[
      [{m:"z^2=(x^2-y^2)+i\\,(2xy)"},{sr:", pa"}," ",{m:"u=x^2-y^2,\\ v=2xy"},"."],
      [{m:"u_x=2x=v_y"}," ",{sr:"i"}," ",{m:"u_y=-2y=-v_x"},"."],
      [{sr:"Uslovi su zadovoljeni, pa je"}," ",{m:"f"}," ",{sr:"analitička."}],
    ]} },
{ n:11, title:{sr:"Tejlorov i Loranov red, singulariteti, reziduumi"},
  lead:[{sr:"Analitička funkcija razvija se u Tejlorov red, a oko singulariteta u Loranov red (sa negativnim stepenima). Koeficijent uz"}," ",{m:"(z-z_0)^{-1}"}," ",{sr:"je reziduum, ključan za teoremu o reziduumima."}],
  zapamti:[
    {label:{sr:"Loranov red"}, tex:"f(z)=\\sum_{n=-\\infty}^{\\infty} c_n\\,(z-z_0)^n"},
    {label:{sr:"Reziduum u prostom polu"}, tex:"\\operatorname{Res}_{z_0}f=\\lim_{z\\to z_0}(z-z_0)\\,f(z)"},
    {label:{sr:"Teorema o reziduumima"}, tex:"\\oint\\limits_C f(z)\\,dz=2\\pi i\\sum \\operatorname{Res} f"},
  ],
  primer:{ task:[{sr:"Naći reziduum funkcije"}," ",{m:"f(z)=\\dfrac{1}{z-2}"}," ",{sr:"u tački"}," ",{m:"z_0=2"},"."],
    steps:[
      [{sr:"Prost pol u"}," ",{m:"z_0=2"},"."],
      [{m:"\\operatorname{Res}_{2}f=\\lim_{z\\to2}(z-2)\\cdot\\dfrac{1}{z-2}=1"},"."],
      [{sr:"Po teoremi:"}," ",{m:"\\oint\\limits_C f\\,dz=2\\pi i\\cdot 1=2\\pi i"},"."],
    ]} },
{ n:12, title:{sr:"Konformna preslikavanja"},
  lead:[{sr:"Konformno preslikavanje čuva uglove. Svaka analitička funkcija sa"}," ",{m:"f'(z)\\neq0"}," ",{sr:"je konformna. Posebno je važna Mebijusova (bilinearna) transformacija."}],
  zapamti:[
    {label:{sr:"Uslov konformnosti"}, tex:"f\\ \\text{analitička},\\ f'(z)\\neq0\\ \\Rightarrow\\ \\text{čuva uglove}"},
    {label:{sr:"Mebijusova transformacija"}, tex:"w=\\frac{az+b}{cz+d},\\qquad ad-bc\\neq0"},
  ],
  primer:{ task:[{sr:"Da li je"}," ",{m:"f(z)=z^2"}," ",{sr:"konformno u tački"}," ",{m:"z=1"},"?"],
    steps:[
      [{sr:"Izvod:"}," ",{m:"f'(z)=2z"},"."],
      [{m:"f'(1)=2\\neq0"},"."],
      [{sr:"Jeste konformno u"}," ",{m:"z=1"}," ",{sr:"(jedino u"}," ",{m:"z=0"}," ",{sr:"nije, jer je tamo"}," ",{m:"f'=0"},")."],
    ]} },
{ n:13, title:{sr:"Furijeov red i transformacija"},
  lead:[{sr:"Furijeov red razlaže periodičnu funkciju na sinuse i kosinuse. Za neperiodične funkcije koristi se Furijeova transformacija. Parne funkcije daju kosinusni, a neparne sinusni red."}],
  zapamti:[
    {label:{sr:"Furijeov red"}, tex:"f(x)=\\frac{a_0}{2}+\\sum_{n=1}^{\\infty}\\big(a_n\\cos nx+b_n\\sin nx\\big)"},
    {label:{sr:"Koeficijent uz kosinus"}, tex:"a_n=\\frac{1}{\\pi}\\int_{-\\pi}^{\\pi} f(x)\\cos nx\\,dx"},
    {label:{sr:"Koeficijent uz sinus"}, tex:"b_n=\\frac{1}{\\pi}\\int_{-\\pi}^{\\pi} f(x)\\sin nx\\,dx"},
    {label:{sr:"Furijeova transformacija"}, tex:"F(\\omega)=\\int_{-\\infty}^{\\infty} f(t)\\,e^{-i\\omega t}\\,dt"},
  ],
  primer:{ task:[{sr:"Odrediti koeficijent"}," ",{m:"a_0"}," ",{sr:"za"}," ",{m:"f(x)=x"}," ",{sr:"na intervalu"}," ",{m:"(-\\pi,\\pi)"},"."],
    steps:[
      [{m:"a_0=\\dfrac{1}{\\pi}\\displaystyle\\int_{-\\pi}^{\\pi} x\\,dx"},"."],
      [{sr:"Funkcija"}," ",{m:"x"}," ",{sr:"je neparna, pa je integral po simetričnom intervalu jednak"}," ",{m:"0"},"."],
      [{m:"a_0=0"},{sr:"; razvoj sadrži samo sinusne članove."}],
    ]} },
{ n:14, title:{sr:"Laplasova transformacija"},
  lead:[{sr:"Laplasova transformacija prevodi funkciju vremena u funkciju kompleksne promenljive"}," ",{m:"s"},{sr:". Pretvara diferencijalne jednačine u algebarske, pa je nezamenljiva u elektrotehnici i teoriji sistema."}],
  zapamti:[
    {label:{sr:"Definicija"}, tex:"\\mathcal{L}\\{f\\}(s)=\\int_0^{\\infty} f(t)\\,e^{-st}\\,dt"},
    {label:{sr:"Osnovne transformacije"}, tex:"\\mathcal{L}\\{1\\}=\\frac1s,\\quad \\mathcal{L}\\{e^{at}\\}=\\frac{1}{s-a}"},
    {label:{sr:"Transformacija izvoda"}, tex:"\\mathcal{L}\\{f'\\}=s\\,F(s)-f(0)"},
  ],
  primer:{ task:[{sr:"Naći Laplasovu transformaciju funkcije"}," ",{m:"f(t)=e^{2t}"},"."],
    steps:[
      [{m:"\\mathcal{L}\\{e^{2t}\\}=\\displaystyle\\int_0^{\\infty} e^{2t}e^{-st}\\,dt=\\int_0^{\\infty} e^{-(s-2)t}\\,dt"},"."],
      [{sr:"Integral konvergira za"}," ",{m:"s>2"},"."],
      [{m:"\\mathcal{L}\\{e^{2t}\\}=\\dfrac{1}{s-2}"},"."],
    ]} },
];
module.exports = { skripta };
