-- Migracija naziv->kljuc za postojece redove u pretplate.predmeti
with mapa(naziv, kljuc) as (values
  ('Matematika 5. razred','osn-mat-5'),
  ('Matematika 6. razred','osn-mat-6'),
  ('Matematika 7. razred','osn-mat-7'),
  ('Matematika 8. razred','osn-mat-8'),
  ('Fizika 6. razred','osn-fiz-6'),
  ('Fizika 7. razred','osn-fiz-7'),
  ('Fizika 8. razred','osn-fiz-8'),
  ('Mala matura','mala-matura'),
  ('Matematika 1. razred','sr-mat-1'),
  ('Matematika 2. razred','sr-mat-2'),
  ('Matematika 3. razred','sr-mat-3'),
  ('Matematika 4. razred','sr-mat-4'),
  ('Fizika 1. razred','sr-fiz-1'),
  ('Fizika 2. razred','sr-fiz-2'),
  ('Fizika 3. razred','sr-fiz-3'),
  ('Fizika 4. razred','sr-fiz-4'),
  ('Algebra','algebra'),
  ('Matematička analiza 1','analiza1'),
  ('Matematička analiza 2','analiza2'),
  ('Linearna algebra','linearna-algebra'),
  ('Diskretna matematika','diskretna-matematika'),
  ('Kompleksna analiza','kompleksna-analiza'),
  ('Verovatnoća i statistika','verovatnoca'),
  ('Operaciona istraživanja','operaciona'),
  ('Teorija električnih kola','elektrotehnika'),
  ('Električna merenja','elektricna-merenja'),
  ('Uvod u elektroniku','uvod-u-elektroniku'),
  ('Elektrodistributivni sistemi','elektrodistributivni-sistemi'),
  ('Osnovi elektrotehnike 1','osnovi-elektrotehnike'),
  ('Osnovi elektrotehnike 2','osnovi-elektrotehnike'),
  ('Elektromagnetika','elektromagnetika'),
  ('Sistemi i signali','sistemi-signali'),
  ('Merenja neelektričnih veličina','elektricna-merenja'),
  ('Energetska elektronika 1','energetska-elektronika-1'),
  ('Energetska elektronika 2','energetska-elektronika-2'),
  ('Električne mašine 1','elektricne-masine'),
  ('Električne mašine 2','elektricne-masine'),
  ('Električne mašine 3','elektricne-masine'),
  ('Elektroenergetski pretvarači','elektroenergetski-pretvaraci'),
  ('Mehanika','mehanika'),
  ('Objektno orijentisano programiranje','cpp'),
  ('Baze podataka 1','fax-bazepodataka'),
  ('Baze podataka 2','fax-bazepodataka'),
  ('Web programiranje','web'),
  ('Python','python'),
  ('C++','cpp'),
  ('C#','csharp'),
  ('Java','java'),
  ('JavaScript','js'),
  ('TypeScript','js'),
  ('Kotlin','kotlin'),
  ('Swift','cpp'),
  ('Go','algoritmi'),
  ('PHP','web'),
  ('C','cpp'),
  ('Pascal','pascal'),
  ('R','r'),
  ('SQL','fax-bazepodataka'),
  ('Veb (HTML, CSS, JS)','web'),
  ('Algoritmi i strukture','algoritmi'),
  ('MATLAB','matlab'),
  ('Scratch','scratch'),
  ('Arduino','arduino'),
  ('KiCad','kicad'),
  ('Cadence','cadence'),
  ('Priprema – srednja škola','priprema-srednja'),
  ('Priprema – viša škola','priprema-visa'),
  ('Priprema za upis na fakultet','priprema-fakultet'),
  ('Prijemni iz matematike','prijemni-ftn'),
  ('Prijemni: matematika sa logikom','prijemni'),
  ('Prijemni: test sklonosti','prijemni'),
  ('Rešeni rokovi 2012–2025','prijemni'),
  ('LabVIEW','labview'),
  ('LTSpice','ltspice'),
  ('PSpice','pspice'),
  ('Mehanika fluida','fax-mehanika-fluida'),
  ('Termodinamika','fax-termodinamika'),
  ('Materijali u elektrotehnici','fax-materijali-et'),
  ('Impulsna elektronika','fax-impulsna-elektronika'),
  ('Digitalna elektronika','fax-digitalna-elektronika'),
  ('Elektronika — pojačavači','fax-elektronika-pojacavaci')
)
update pretplate p set predmeti = sub.novi from (
  select p2.id, (select jsonb_agg(distinct coalesce(m.kljuc, e.elem))
     from jsonb_array_elements_text(p2.predmeti) as e(elem)
     left join mapa m on m.naziv = e.elem) as novi
  from pretplate p2 where p2.predmeti is not null and jsonb_typeof(p2.predmeti)='array') sub
where p.id=sub.id and p.predmeti is distinct from sub.novi;