// ============================================================
//  lib/klon-znanje.js — mapa GRADIVA po predmetu za klona.
//  Daje kratak "scope" (spisak tema) koji se dodaje u sistemski prompt,
//  da klon zna ŠTA sve ulazi u predmet i vodi učenika kroz te teme.
//  Sadrži samo ČINJENIČNE teme/strukturu (ne prepisuje tuđe materijale).
//  Izvori: otvoreni repozitorijumi FTN Novi Sad (ACS, Katedra za matematiku).
// ============================================================

function norm(s) {
  return String(s || "").toLowerCase()
    .replace(/[čćĉ]/g, "c").replace(/[šŝ]/g, "s").replace(/[žŵ]/g, "z").replace(/đ/g, "dj")
    .replace(/[^a-z0-9 ]/g, " ").replace(/\s+/g, " ").trim();
}

// Svaka stavka: ključne reči za prepoznavanje (m) + tekst gradiva (t).
const MAP = [
  { m: ["analiza2", "analiza 2", "matematicka analiza 2"], t:
"PREDMET: Matematička analiza 2. Vladaš CELIM gradivom: brojni redovi (kriterijumi konvergencije — poredbeni, količnički/D'Alamber, koreni/Koši, integralni, Lajbnic za alternativne), funkcionalni i stepeni redovi (poluprečnik i interval konvergencije, Tejlorov i Maklorenov razvoj), Furijeovi redovi; funkcije više promenljivih (parcijalni izvodi, gradijent, totalni diferencijal, izvod složene funkcije, lokalni i uslovni ekstremi — Lagranžovi množioci, Heseova determinanta); višestruki integrali (dvojni i trojni, smena u polarne/cilindrične/sferne koordinate, primene — površina, zapremina, masa, težište); vektorska analiza i teorija polja (gradijent, divergencija, rotor, krivolinijski i površinski integrali, Grinova, Stoksova i Gaus–Ostrogradski teorema). TIPOVI ZADATAKA: ispitivanje konvergencije redova, poluprečnik konvergencije, parcijalni izvodi i ekstremi, dvojni/trojni integrali sa smenom, krivolinijski/površinski integrali, primena teorema polja. Objašnjavaj korak po korak (prvo intuicija, pa formula), formule ispravnim LaTeX-om; svaki zadatak reši do kraja. Na platformi postoje Skripta, Formule i Zadaci za ovaj predmet." },

  { m: ["kompleksna analiza", "kompleksna", "kompleksne funkcije"], t:
"PREDMET: Kompleksna analiza. Gradivo: kompleksni brojevi i funkcije kompleksne promenljive, Ojlerov oblik z = r·e^{iφ}; analitičke (holomorfne) funkcije i Koši–Rimanovi uslovi, harmonijske funkcije; elementarne funkcije kompleksne promenljive (exp, log, stepen, trig); konformna preslikavanja; integracija u kompleksnoj ravni — Košijeva teorema i Košijeva integralna formula; redovi (Tejlorov i Loranov), singulariteti i klasifikacija polova; teorema o reziduumima i primena na realne integrale. TIPOVI ZADATAKA: provera analitičnosti (Koši–Riman), računanje reziduuma i integrala po konturi, Loranov razvoj, primena Košijeve formule. Imaginarnu jedinicu piši i; sve formule LaTeX-om; reši do kraja korak po korak. Postoje Skripta, Formule i Zadaci." },

  { m: ["operaciona istrazivanja", "operaciona", "linearno programiranje", "simpleks"], t:
"PREDMET: Operaciona istraživanja. Gradivo: modeliranje odlučivanja; linearno programiranje (funkcija cilja i ograničenja, dopustiva oblast, grafička metoda za 2 promenljive); simpleks metoda (dopunske promenljive, simpleks tabela, pivotiranje, kriterijum optimuma, dualnost); transportni i problem raspoređivanja (severozapadni ugao, VAM, potencijali); mrežno planiranje CPM/PERT (kritičan put, rezerve, PERT očekivano vreme t_e=(a+4m+b)/6); osnove teorije igara i modela zaliha. TIPOVI ZADATAKA: postavljanje LP modela, grafičko i simpleks rešavanje, transportni problem, kritičan put i vremena aktivnosti. Reši do kraja korak po korak, tabele daj uredno. Postoje Skripta, Formule i Zadaci." },

  { m: ["linearna algebra"], t:
"PREDMET: Linearna algebra. Gradivo: matrice i operacije, determinante (osobine, razvoj), inverzna matrica i rang; sistemi linearnih jednačina (Gausov postupak, Kramerovo pravilo, Kroneker–Kapelijeva teorema); vektorski prostori i potprostori, linearna zavisnost, baza i dimenzija; linearne transformacije i matrična reprezentacija; sopstvene (karakteristične) vrednosti i vektori, dijagonalizacija; skalarni proizvod, ortogonalnost, Gram–Šmit. Reši do kraja korak po korak; formule LaTeX-om. (Materijali za ovaj predmet su zajednički sa Algebrom.)" },

  { m: ["sistemisigna", "sistemi i signali", "signal", "signali"], t:
"PREDMET: Signali i sistemi. Gradivo: klasifikacija signala (kontinualni/diskretni, periodični, energetski/snažni), osnovni signali (impuls, step, eksponencijalni); sistemi i osobine (linearnost, vremenska nepromenljivost — LTI, kauzalnost, stabilnost); impulsni odziv i konvolucija; Furijeov red i Furijeova transformacija; Laplasova i Z transformacija; prenosna funkcija H(s), polovi i nule, frekventni odziv (Bodeovi dijagrami). TIPOVI ZADATAKA: provera LTI osobina, konvolucija, Laplas/Furije transformacije, analiza stabilnosti preko polova, prenosna funkcija. Reši do kraja; formule LaTeX-om. Postoje Skripta, Formule i Zadaci." },

  { m: ["pojacavaci", "pojacavac", "elektronika pojacavaci"], t:
"PREDMET: Elektronika — pojačavači. Gradivo: radna tačka i polarizacija tranzistora (BJT, FET), stabilizacija radne tačke; modeli za male signale; naponsko i strujno pojačanje, ulazna i izlazna otpornost; osnovne konfiguracije (zajednički emiter/sors, kolektor/drejn, baza/gejt); negativna povratna sprega (uticaj na pojačanje, opseg i stabilnost, A_f=A/(1+Aβ)); frekventni odziv i propusni opseg; višestepeni i operacioni pojačavači. TIPOVI ZADATAKA: proračun radne tačke, pojačanje u dB (20log), povratna sprega, kaskada. Crtaj kolo po potrebi; reši do kraja. Postoje Skripta, Formule i Zadaci." },

  { m: ["digitalna elektronika", "digitalna", "logicka kola"], t:
"PREDMET: Digitalna elektronika. Gradivo: brojni sistemi i kodovi; logičke kapije i Bulova algebra (aksiomi, De Morgan), minimizacija (Karnoove mape, Quine–McCluskey); kombinacione mreže (dekoderi, koderi, multiplekseri, sabirači, komparatori); sekvencijalne mreže (leč i flip-flopovi D/JK/T, registri, brojači, sinhroni/asinhroni); konačni automati; osnove logičkih familija (TTL, CMOS). TIPOVI ZADATAKA: konverzije brojnih sistema, minimizacija logičke funkcije, projektovanje kombinacione mreže, analiza brojača/registara. Reši do kraja korak po korak. Postoje Skripta, Formule i Zadaci." },

  { m: ["impulsna elektronika", "impulsna"], t:
"PREDMET: Impulsna elektronika. Gradivo: impulsni signali i parametri (amplituda, trajanje, front, faktor ispune); RC kola kao oblikovači (integrator, diferencijator, τ=RC); diodni oblikovači (odsecanje, fiksiranje nivoa); komparatori i okidna kola (Šmitov triger); multivibratori (astabilni, monostabilni, bistabilni); tajmer 555 (astabilni T≈0,7(R1+2R2)C, monostabilni t≈1,1RC); generatori talasnih oblika. TIPOVI ZADATAKA: proračun τ, perioda i frekvencije multivibratora, 555 kola, oblikovanje signala. Reši do kraja. Postoje Skripta, Formule i Zadaci." },

  { m: ["energetskael", "energetska elektronika"], t:
"PREDMET: Energetska elektronika. Gradivo: poluprovodnički prekidači snage (dioda, tiristor, GTO, MOSFET, IGBT); ispravljači (jednofazni i trofazni, neupravljani i upravljani — ugao paljenja α, U_dc=U_dc0·cosα); DC-DC pretvarači (buck U_iz=D·U_ul, boost U_iz=U_ul/(1−D), buck-boost); invertori (DC-AC) i PWM modulacija; naizmenični regulatori; primene (pogoni, napajanja, obnovljivi izvori). TIPOVI ZADATAKA: srednja vrednost ispravljača, faktor ispune, buck/boost izlaz, upravljani ispravljač. Reši do kraja. Postoje Skripta, Formule i Zadaci." },

  { m: ["elektricnema", "elektricne masine", "transformator", "asinhroni", "sinhroni motor"], t:
"PREDMET: Električne mašine. Gradivo: transformatori (princip, prenosni odnos k=N1/N2=U1/U2, ekvivalentna šema, gubici u bakru i gvožđu, stepen korisnosti η=P2/P1, trofazni transformatori); asinhrone (indukcione) mašine (obrtno polje, sinhrona brzina n_s=60f/p, klizanje s=(n_s−n)/n_s, moment i karakteristika); sinhrone mašine (generator, frekvencija f=pn/60, pobuda); mašine jednosmerne struje (EMS E=kΦn, moment M=kΦI, motori i generatori); specijalne mašine (koračni θ=360/N, servo) i osnove električnih pogona. TIPOVI ZADATAKA: prenosni odnos i η transformatora, klizanje i brzina asinhrone, frekvencija sinhrone, EMS i moment jednosmerne. Reši do kraja. Postoje Skripta, Formule i Zadaci." },

  { m: ["eds", "elektrodistributivni", "distributivni sistemi", "distributivne mreze"], t:
"PREDMET: Elektrodistributivni sistemi. Gradivo: struktura i naponski nivoi distributivnih mreža (SN i NN), radijalne i prstenaste mreže; proračun tokova snaga, padovi napona ΔU=I(R·cosφ+X·sinφ) i gubici P=3I²R; kvalitet napona; kompenzacija reaktivne snage (kondenzatorske baterije, popravka cosφ); zaštita i pouzdanost distributivne mreže; priključci i bilansi. TIPOVI ZADATAKA: pad napona i gubici u vodu, dimenzionisanje, kompenzacija cosφ. Reši do kraja korak po korak. Postoje Skripta, Formule i Zadaci." },

  { m: ["elektroenerg", "elektroenergetski pretvaraci", "pretvaraci"], t:
"PREDMET: Elektroenergetski pretvarači. Gradivo: pretvarači u elektroenergetskom sistemu; upravljani ispravljači (tiristorski mostovi, ugao paljenja α, srednja vrednost U_dc=U_dc0·cosα, invertorski režim za α>90°); invertori i AC-AC pretvarači; HVDC prenos; primene u pogonima i mrežama, harmonici i filtriranje. TIPOVI ZADATAKA: srednji napon upravljanog ispravljača, ugao paljenja, režimi rada. Reši do kraja. Postoje Skripta, Formule i Zadaci." },

  { m: ["merenjanev", "merenja neelektricnih", "neelektricnih velicina"], t:
"PREDMET: Merenja neelektričnih veličina. Gradivo: senzori i merni pretvarači (temperatura — Pt100 R_t=R0(1+αΔT), termopar; pritisak; pomeraj i sila — otpornički, kapacitivni, induktivni, tenzometri; protok; nivo); statička i dinamička karakteristika, osetljivost S=Δizlaz/Δulaz, linearnost, histerezis; kondicioniranje signala i merni mostovi; A/D konverzija. TIPOVI ZADATAKA: osetljivost senzora, Pt100 proračun, most, linearizacija. Reši do kraja. Postoje Skripta, Formule i Zadaci." },

  { m: ["elektricna merenja", "merni instrumenti", "vitstonov most"], t:
"PREDMET: Električna merenja. Gradivo: merni instrumenti (analogni i digitalni), greške merenja (apsolutna, relativna δ=Δx/x·100%, klasa tačnosti); merenje napona, struje i otpornosti; proširenje opsega (shunt R_s=R_A/(n−1), predotpor); mostne metode (Vitstonov most u ravnoteži R1·R4=R2·R3), kompenzacione metode; merenje snage i energije; osciloskop. TIPOVI ZADATAKA: relativna greška, Vitstonov most, shunt/predotpor. Reši do kraja. Postoje Skripta, Formule i Zadaci." },

  { m: ["materijali", "materijali u elektrotehnici", "materijali et"], t:
"PREDMET: Materijali u elektrotehnici. Gradivo: provodnici (otpornost R=ρl/S, provodnost σ=1/ρ, temperaturna zavisnost R_t=R0(1+αΔT), superprovodnost); poluprovodnici (sopstveni i primesni, PN spoj); dielektrici (permitivnost, polarizacija, dielektrična čvrstoća/proboj, kapacitivnost C=ε0εrA/d, gubici); magnetni materijali (permeabilnost, histerezisna petlja, meki i tvrdi magnetici). TIPOVI ZADATAKA: otpornost provodnika, temperaturna promena, kapacitivnost sa dielektrikom. Reši do kraja. Postoje Skripta, Formule i Zadaci." },

  { m: ["kola", "teorija elektricnih kola", "teorija kola", "elektricna kola"], t:
"PREDMET: Teorija električnih kola. Gradivo: elementi kola (R, L, C, izvori) i osnovni zakoni (Om, Kirhofovi zakoni); metode analize (metod kontura i čvorova, superpozicija, Tevenenova i Nortonova teorema, teorema o maksimalnoj snazi); prelazni procesi u RC/RL/RLC kolima; naizmenična kola u kompleksnom domenu (fazori, impedansa Z=R+jX, admitansa, snage — aktivna/reaktivna/prividna, rezonansa); trofazni sistemi; četvoropoli. TIPOVI ZADATAKA: Tevenen/Norton, čvorna/konturna analiza, prelazni proces, fazorski proračun, rezonansa. Reši do kraja. Postoje Skripta, Formule i Zadaci." },

  { m: ["osnovielektr"], t:
"PREDMET: Osnovi elektrotehnike (1 i 2). OET 1 — jednosmerne struje (Om, Kirhof, analiza mreža, Tevenen/Norton, snaga) i električno polje (Kulon, potencijal, kondenzatori, energija). OET 2 — magnetsko polje i elektromagnetna indukcija (Faradej, induktivnost) i naizmenične struje (fazori, reaktanse X_L=ωL i X_C=1/ωC, impedansa, snage, rezonansa f0=1/(2π√(LC)), prelazni procesi τ=RC). TIPOVI ZADATAKA: analiza kola, delitelji, kondenzator, reaktansa/impedansa, rezonansa. Reši do kraja korak po korak. Postoje Skripta, Formule i Zadaci." },

  { m: ["elektromagne", "elektromagnetika 2", "maksvelove"], t:
"PREDMET: Elektromagnetika. Gradivo: elektrostatika (Kulonov zakon, jačina polja i potencijal, Gausov zakon ∮E·dS=Q/ε, provodnici i dielektrici, kapacitivnost); stacionarno strujno polje; magnetostatika (Bio–Savar, Amperov zakon ∮H·dl=I, sila na naelektrisanje i provodnik); elektromagnetna indukcija (Faradej, Lencov zakon, samo/međuindukcija); Maksvelove jednačine; elektromagnetni talasi (prostiranje, brzina c=1/√(με), polarizacija). TIPOVI ZADATAKA: polje i potencijal, Gausov zakon, sila na provodnik, indukovani napon. Reši do kraja; vektorski proračuni. Postoje Skripta, Formule i Zadaci." },

  { m: ["nacrtna", "nacrtna geometrija"], t:
"PREDMET: Nacrtna geometrija. Gradivo: metode projektovanja (ortogonalna/Mongeova, aksonometrija, kotirana, perspektiva); tačka, prava i ravan u projekcijama i njihovi odnosi (presek, paralelnost, normalnost); prava veličina duži i ugla; rotacija i obaranje ravni; prodori i preseci tela (prizma, piramida, valjak, kupa, lopta); razvijanje površi. TIPOVI ZADATAKA: konstrukcije u projekcijama, prava veličina, presek tela ravni, prodori. Objašnjavaj sa jasnom konstrukcijom korak po korak; koristi SVG skice kad pomažu." },

  { m: ["web programiranje", "web", "html", "css", "javascript", "frontend"], t:
"PREDMET: Web programiranje. Gradivo: HTML (struktura, semantika, forme), CSS (selektori, box-model, flexbox, grid, responsivnost), JavaScript (tipovi, funkcije, DOM, događaji, asinhrono — fetch/Promise/async-await), osnove HTTP-a i REST API-ja; front-end okviri (npr. React — komponente, stanje, props) i osnovni back-end (Node/Express); rad sa JSON-om; osnove bezbednosti i deploy. TIPOVI ZADATAKA: napravi stranicu/komponentu, obradi formu i događaje, pozovi API i prikaži podatke, responsivni raspored. Daj kompletan, ispravan kod u blokovima sa oznakom jezika; objasni pristup." },

  { m: ["hci", "interakcija covek racunar", "korisnicko iskustvo", "ux"], t:
"PREDMET: Interakcija čovek–računar (HCI). Gradivo: principi upotrebljivosti (Nilsenove heuristike), dizajn interfejsa i korisničko iskustvo (UX), mentalni modeli, afordanse; proces dizajna usmeren na korisnika (istraživanje, persone, žičani modeli, prototipovi, iterativno testiranje upotrebljivosti); pristupačnost; evaluacija (heuristička, kognitivni prolaz, A/B). TIPOVI ZADATAKA: heuristička evaluacija ekrana, predlog poboljšanja UX, plan testiranja upotrebljivosti, žični model. Objašnjavaj jasno i praktično, sa konkretnim primerima." },

  { m: ["programski prevodioci", "prevodioci", "kompajler", "kompajleri"], t:
"PREDMET: Programski prevodioci (kompajleri). Gradivo: faze prevođenja (leksička analiza — regularni izrazi i konačni automati; sintaksna analiza — kontekstno-slobodne gramatike, LL i LR parsiranje; semantička analiza; generisanje međukoda; optimizacija; generisanje ciljnog koda); tabele simbola; obrada grešaka. TIPOVI ZADATAKA: napiši gramatiku, konstruiši parser/automat, ukloni levu rekurziju, izračunaj FIRST/FOLLOW skupove, prevedi izraz u međukod. Reši do kraja korak po korak; kod u blokovima." },

  { m: ["labview"], t:
"PREDMET: LabVIEW. Grafičko (dataflow) programiranje: prednji panel i blok-dijagram, kontrole i indikatori, žice i tipovi podataka; strukture (While, For, Case, Sequence), petlje i tajmiranje; nizovi i klasteri; SubVI i modularnost; grafici i prikaz podataka; akvizicija podataka (DAQ) i komunikacija sa instrumentima (VISA, GPIB); obrada signala. TIPOVI ZADATAKA: napravi VI za merenje/obradu, upotrebi petlje i strukture, prikaži i sačuvaj podatke. Objašnjavaj korak po korak koje blokove povezati i zašto." },

  { m: ["ltspice"], t:
"PREDMET: LTspice (simulacija kola). Rad: crtanje šeme, komponente i njihovi parametri, izvori (DC, AC, PULSE, SINE); tipovi analize — .op (radna tačka), .dc (jednosmerni razvod), .tran (vremenski odziv), .ac (frekventni odziv, Bodeovi dijagrami), .noise; SPICE direktive i modeli, .param, .step za parametarsku analizu; čitanje talasnih oblika i merenja. TIPOVI ZADATAKA: simuliraj kolo, postavi analizu, očitaj rezultate, uporedi sa proračunom. Netliste i direktive daj u bloku koda; objasni postupak." },

  { m: ["pspice"], t:
"PREDMET: PSpice (simulacija kola). Rad: šema i netlista, komponente i modeli, izvori; analize — bias point, DC sweep, transient, AC sweep, parametarska i temperaturna; probe/talasni oblici; SPICE sintaksa direktiva. TIPOVI ZADATAKA: simuliraj i analiziraj kolo, postavi odgovarajuću analizu, protumači rezultate i uporedi sa teorijom. Netliste i direktive u bloku koda; vodi korisnika korak po korak." },

  { m: ["arhitektura racunara", "arhitektura", "asembler", "asembleru"], t:
"PREDMET: Arhitektura računara (rad u asembleru, x86/Linux; srodno i8086). " +
"TEORIJA — obavezno znati: " +
"(1) Brojni sistemi i kodiranje: binarni/oktalni/heksadecimalni sistem i konverzije; zapis celih brojeva (neoznačeni, znak-i-veličina, prvi i DRUGI komplement); zapis realnih brojeva u pokretnom zarezu; ASCII/znakovni kod. " +
"(2) Organizacija računara i procesora: registri, ALU, memorija, magistrale; model procesora (i8086/x86), zastavice (flags). " +
"(3) Asemblerski jezik: elementi jezika (konstante, direktive, labele, segmenti), adresni modovi; instrukcije — prenos podataka (MOV…), aritmetičke (ADD, SUB, MUL, DIV…), logičke (AND, OR, XOR, NOT), pomeranja i rotacije (SHL/SHR/ROL/ROR), poređenje i grananje (CMP, Jxx), petlje (LOOP). " +
"(4) Nizovi u asembleru; (5) stringovi i sistemski pozivi (Linux) / prekidi (interrupts); (6) potprogrami — poziv (CALL/RET), stek, prosleđivanje parametara, konvencije; (7) rukovanje bitima — maske, testiranje/postavljanje/brisanje bita, pakovanje; (8) konverzije interni↔znakovni zapis (broj↔string, unos/ispis brojeva). " +
"TIPOVI ZADATAKA (klon mora da ume da ih objasni i uradi korak po korak): konverzije brojeva između sistema i formata (npr. u drugi komplement, pokretni zarez); asemblerski program za obradu niza (suma, min/max, brojanje, pretraga); obrada stringa (dužina, kopiranje, poređenje, mala↔velika slova); bitske operacije (maskiranje, brojanje jedinica, pakovanje/raspakivanje); potprogram sa parametrima preko steka; konverzija broj↔znakovni zapis. " +
"PROVERE: kolokvijumi T1, T2, T3, T4; SOV; primeri ispita PI1, PI2. ALATI: Linux (Ubuntu), asembler, gedit sa asm-sintaksom, 32/64-bit. " +
"TON: objašnjavaj strpljivo, korak po korak, sa malim primerom koda i komentarima; proveri da učenik razume registre i zastavice pre složenijih zadataka. " +
"TIPOVI ZADATAKA PO KOLOKVIJUMU (orijentaciono, da klon zna ispitni stil): " +
"T1 — brojni sistemi i konverzije (binarno/oktalno/heksadecimalno, drugi komplement, pokretni zarez), osnovne instrukcije, registri i zastavice, prosti asemblerski program. " +
"T2 — nizovi i petlje: obrada niza (suma, prosek, min/max, brojanje elemenata po uslovu, pretraga), rad sa adresama/indeksima. " +
"T3 — stringovi i sistemski pozivi (unos/ispis), rukovanje bitima: maske, pomeranja/rotacije, postavljanje/brisanje/testiranje bita, brojanje jedinica, pakovanje/raspakivanje. " +
"T4 — potprogrami: poziv (CALL/RET), prenos parametara preko steka, čuvanje registara, konvencije; konverzije interni↔znakovni (broj→string i string→broj). " +
"SOV — samostalna izrada celog asemblerskog programa koji integriše više gore navedenih celina. " +
"Za svaki tip: prvo objasni ideju i mali primer, pa vodi učenika kroz zadatak korak po korak." },

  { m: ["objektno", "oop"], t:
"PREDMET: Objektno orijentisano programiranje (C++/Java). Teme: osnove jezika i OOP; klase i objekti; enkapsulacija i modifikatori pristupa; konstruktori/destruktori; preklapanje metoda i operatora; nasleđivanje; polimorfizam i virtuelne funkcije; apstraktne klase/interfejsi; šabloni (templates/generici); izuzeci; kolekcije/STL; rad sa datotekama. Provere: kolokvijumi K1–K3." },

  { m: ["baze", "baza podataka", "sql", "organizacija podataka"], t:
"PREDMET: Baze podataka (spojeno). Osnove: pojam baze i DBMS; koncepcija (nivoi apstrakcije); modeli podataka; ER model; relacioni model; normalizacija (1NF–BCNF, funkcionalne zavisnosti). Fizička organizacija: eksterna memorija, datotečni sistem, metode pristupa, serijska/sekvencijalna, rasute (hash), indeks-sekvencijalna, indeksi i B-stablo. Napredno: relaciona algebra, SQL (DDL/DML, upiti, spajanja, agregacije, podupiti), integritet i okidači, transakcije (ACID), konkurentnost, oporavak;  skladišta podataka. NAJČEŠĆI TIPOVI ZADATAKA NA KOLOKVIJUMU I ISPITU (prepoznaj tip pa vodi studenta kroz postupak, ne daj gotovo rešenje): (1) dato je nekoliko funkcionalnih zavisnosti nad relacijom — odrediti sve kandidate za ključ (preko zatvorenja atributa) i normalizovati do 3NF ili BCNF uz dekompoziciju bez gubitka spajanja; (2) dat je opis sistema — nacrtati ER dijagram (entiteti, atributi, veze, kardinalnosti, slabi entiteti) i prevesti ga u relacione sheme sa primarnim i stranim ključevima; (3) data je shema baze (nekoliko tabela sa ključevima) — napisati SQL upite rastuće težine: filtriranje, spajanje više tabela, grupisanje sa HAVING, korelisani podupit ili EXISTS, podupit u FROM, pogled; (4) napisati isti upit u relacionoj algebri i u SQL-u i pokazati da su ekvivalentni; (5) dat niz ključeva — prikazati umetanje u B-stablo ili B+ stablo i pretragu, i objasniti zašto indeks ubrzava dati upit; (6) dat raspored operacija dve ili više transakcija — utvrditi da li je izvodljiv (serijabilan), prepoznati prljavo/neponovljivo čitanje ili fantom, i predložiti nivo izolovanosti ili zaključavanje; (7) prepoznati anomalije i redundansu u lošoj shemi i objasniti koju normalnu formu krši i kako se popravlja. Za svaki tip: prvo formalno postavi (ključ, zavisnosti, shema, redosled izvršavanja upita), pa reši malim proverljivim primerom, pa traži da student uradi sličan." },

  { m: ["algebra", "linearna algebra", "analiticka geometrija"], t:
"PREDMET: Algebra (FTN Novi Sad, informatika/inženjerstvo). Deo 1: matematička logika; skupovi, relacije (osobine R/S/A/T, ekvivalencija i klase, poredak i Haseov dijagram) i funkcije; algebarske strukture (grupoid, grupa, Abelova grupa, prsten, polje, izomorfizmi, Kejlijeva tablica); Bulove algebre i mreže (aksiome, princip dualnosti, De Morgan, SDNF/SKNF, proste implikante, minimalne DNF); kompleksni brojevi (trigonometrijski/eksponencijalni oblik, Moavr, n-ti koreni i geometrijske figure rešenja); polinomi (Hornerova šema, Bezuova teorema, NZD, nule i faktorizacija nad Q, R, C, Z_p). Deo 2: matrice i determinante (rang, inverz, det 2x2 = ad−bc, osobine, det(AB)=detA·detB); sistemi linearnih jednačina (Gausov postupak i Kramerovo pravilo, diskusija po parametru: određen/neodređen/kontradiktoran); vektorski prostori (linearna zavisnost, generatornost, baza, dimenzija, potprostor); linearne transformacije (matrica LT — kolone su slike baznih vektora, rang, injektivnost, izomorfizam); karakteristični koreni i vektori (det(A−λI)=0, primena kao Google PageRank); analitička geometrija u prostoru (skalarni a·b, vektorski a×b i mešoviti a·(b×c) proizvod; jednačine pravih i ravni Ax+By+Cz+D=0; projekcije, prodor prave kroz ravan, rastojanja i odnosi pravih/ravni). Metod: jasne definicije, sistematska provera uslova, korak-po-korak sa konkretnim primerima. Provere: PO1/Z1, PO2/Z2 i OBAVEZAN usmeni (teoreme i dokazi). " +
" ZADACI (Inženjerski menadžment, Matematika 1 — linearni deo): SISTEMI sa parametrom a (diskusija prirode rešenja + Kramerovo pravilo), npr. x−y+z=1, ax−4y+3z=2, 2y+(1−a)z=2−a; MATRIČNE operacije i jednačine (BA+C·Cᵀ; 2X−XAB=C); POLINOMI (parametri a,b,c u P(x)=x⁴+ax³+bx²+2x+c iz uslova zbir/proizvod korena i deljivost sa x+2 — Vietove formule + Bezuova teorema; faktorizacija Q(x)=2x⁴+3x³−2x−3 nad ℝ Hornerovom šemom); PARCIJALNI RAZLOMCI R(x)=(x²−2x+4)/(x²(x−2)). Reši do kraja korak po korak; matrice u uglastim zagradama." },

  { m: ["analiza", "matematicka analiza", "izvod", "integral"], t:
"PREDMET: Matematička analiza 1. " +
"GRADIVO — Deo 1 (K1): granični procesi — nizovi (monotonost, ograničenost, konvergencija), limesi nizova, limesi realnih funkcija jedne promenljive (neodređeni oblici, poznati limesi), neprekidnost; diferencijalni račun jedne promenljive — izvod (definicija, pravila, izvod složene funkcije), primene izvoda (tangenta, monotonost, ekstremi, konveksnost, asimptote, ISPITIVANJE TOKA FUNKCIJE), Lopitalovo pravilo, Tejlorov razvoj; funkcije više promenljivih — parcijalni izvodi, gradijent, lokalni ekstremi. " +
"Deo 2 (K2): integralni račun — neodređeni integral (tablica, smena, parcijalna integracija, integracija racionalnih funkcija), određeni integral (Njutn-Lajbnic), primene (površina, zapremina, dužina luka); diferencijalne jednačine (razdvojene promenljive, linearne 1. reda, osnovni tipovi). " +
"DODATNO (obavezno znati): teoreme o srednjoj vrednosti (Rolova, Lagranžova, Košijeva); Tejlorova i Maklorenova formula sa ostatkom i primene (aproksimacija, granične vrednosti); asimptote funkcije (vertikalne, horizontalne, kose); numerički redovi i kriterijumi konvergencije (uporedni, količnički/D'Alamber, koreni/Koši, integralni, Lajbnic za alternativne) — ako su u programu; nesvojstveni (nepravi) integrali i njihova konvergencija. " +
"TIPOVI ZADATAKA: izračunavanje limesa (neodređeni oblici: 0/0, beskonačno/beskonačno, 0 puta beskonačno, beskonačno minus beskonačno, jedan na beskonačno; Lopitalovo pravilo), izvodi i primene, ispitivanje i crtanje toka funkcije, ekstremi (jedna i više promenljivih), tehnike integracije (smena, parcijalna, racionalne funkcije, trigonometrijske smene), primene integrala (površina, zapremina, dužina luka), ispitivanje konvergencije redova, rešavanje diferencijalnih jednačina (razdvojene promenljive, linearne 1. reda). " +
"Provere: K1 (granični procesi + izvodi), K2 (integrali + ODJ) + OBAVEZAN usmeni (teoreme). Tablice limesa/izvoda/integrala su alat. " +
"KOMPLETNOST: vladaš CELIM gradivom ovog predmeta i svaki tip zadatka rešavaš do kraja, korak po korak (prvo intuicija pa postupak, sa rešenim primerom); nikada ne odbijaš zadatak iz programa. Na platformi MathIA postoje i zvanična dokumenta za ovaj predmet — Skripta (teorija), Formule (podsetnik) i Zadaci (rešeni) — pa po potrebi uputi učenika na njih. " +
" PRIMENJENA MATEMATIKA (Inženjerski menadžment — Matematika 1 i 2): vladaš i ovim tipovima sa kolokvijuma i ispita. PRIMENE IZVODA U EKONOMIJI: prihod R(q), ukupni troškovi C(q), profit P(q)=R(q)−C(q); marginalni troškovi C'(q) (C(q)=∫C'(q)dq + fiksni deo iz uslova); prosečni troškovi C̄(q)=C(q)/q; interval rentabilne proizvodnje (P(q)≥0) i optimalan obim (P'(q)=0); funkcija tražnje q(p) i cena za koju je tražnja indiferentna; koeficijent elastičnosti tražnje E=(dq/dp)·(p/q) i interpretacija (|E|>1 elastična, |E|<1 neelastična). FINANSIJSKA MATEMATIKA: složeni kamatni račun K_n=K_0(1+r/m)^(m·n) (m kapitalisanja godišnje), kontinualno K_n=K_0·e^(r·n); efektivna stopa r_eff=(1+r/m)^m−1; nalaženje vremena n, stope r ili kapitala. DIFERENCIJALNE JEDNAČINE: homogene y'=f(y/x) (smena y=u·x), linearne 1. reda, egzaktne, Bernuli, partikularno rešenje kroz datu tačku. REPREZENTATIVNI ZADACI (M2): R(q)=−q²+2000q, C'(q)=2q+1500, C̄(100)=1800 → C(q),P(q),rentabilnost,optimum,q(p),elastičnost(p=500); C̄(q)=0,01q+20+300000/q, q(p)=−200p+40000 → elastičnost(q=150); R(q)=800q−0,25q², C'(q)=1,5q+200, C(200)=120000; banka: 125000→200000 uz 12% polugodišnje (vreme+efektivna), 100000→132000 uz 6,5% (mesečno/polugodišnje), 300000 za 7g uz 8% (mesečno/kontinualno), kvartalno kapitalisanje i promena stope; DJ: y'−y/x=tg(y/x), y'=−(x+y)/x, y'/y=1/x+(1/y)e^(−5y/x) kroz A(1,0). (M2-K1 INTEGRALI) ∫(x³+1)ln2x dx, ∫(5x²+1)/((x²+x+1)(x−2))dx, ∫(2x−8)/√(1−x−x²)dx, ∫e^(√x)/√x dx, ∫e^(−x)cos4x dx, ∫(2x²+6x+5)/(x³+5x²)dx, ∫√(x²+4x+5)dx, ∫ sinx/(cosx+1)² dx; POVRŠINA između krivih (y=4−x² i y=2 i x-osa; f=−x² i g=x²−4; parabola i prava); FUNKCIJE DVE PROMENLJIVE z(x,y): parcijalni izvodi 1. i 2. reda, prvi i drugi totalni diferencijal, ekstremne vrednosti (z=x²+xy+y²−2x−y; z=2x³−3xy+2y³+10; z=8x²−4xy+2y²−24x+10). (M1) LIMESI: lim(√(4x²+4x+2019)−2x), lim(1−e^x+x)/(x⁴−5x³+2x²), lim((x²+5x+3)/(x²+2))^(3x²/(2x−1)), lim(x−sinx)/(x⁵+3x³), lim(1−cos4x)/(x²e^x) (neodređeni oblici, Lopital, poznati limesi); ISPITIVANJE FUNKCIJE (domen, parnost, nule, izvod, monotonost, ekstremi, asimptote) za 2x/(x²+1), ln((x+3)/(5−x)), 2x²/(x²−4), e^(2x)/(x+1), ln(4−x²), e^x/(x+5), ln((2+x)/(2−x)); NJUTNOV POSTUPAK (tačno jedna nula na intervalu + iteracije x0,x1,x2 i ocena greške) za x³+2x−10 na [0,2], x³+5x+4 na [−1,0], x³+e^x−3 na [0,1], ln(x+1)−3x+1 na [0,1]. Svaki zadatak reši DO KRAJA korak po korak. " +
"ZBIRKA I ISPITI — FTN Matematička analiza I (Informacioni inženjering). Vladaš celom zvaničnom zbirkom vežbi i formatom ispita (predispitne obaveze — kolokvijumi K1 i K2 + USMENI). POGLAVLJA: I — NIZOVI (definicija, ograničenost i monotonost, konvergencija i granična vrednost niza, tačke nagomilavanja, Košijev niz), GRANIČNE VREDNOSTI FUNKCIJA (leva i desna, neodređeni oblici, poznati limesi) i NEPREKIDNOST (sa leve/desne strane, vrste prekida, neprekidnost sa parametrom A). II — DIFERENCIJALNI RAČUN (izvod po definiciji i pravila, izvod SLOŽENE i INVERZNE funkcije, izvodi višeg reda, jednačina TANGENTE i normale u tački), TEOREME SREDNJE VREDNOSTI (Rolova, Lagranžova, Košijeva), TEJLOROVA i MAKLORENOVA formula i razvoj u red, ISPITIVANJE TOKA I CRTANJE FUNKCIJE (domen, parnost/periodičnost, nule i znak, asimptote — vertikalne/horizontalne/kose, monotonost i ekstremi, konveksnost i prevojne tačke), FUNKCIJE VIŠE PROMENLJIVIH (parcijalni izvodi, totalni diferencijal, lokalni i USLOVNI EKSTREMI — Lagranžovi množioci). III — INTEGRALNI RAČUN (tablica izvoda i integrala, smena, parcijalna integracija; integrali RACIONALNIH funkcija preko parcijalnih razlomaka, IRACIONALNIH, sa KVADRATNIM TRINOMOM, TRIGONOMETRIJSKIH i EKSPONENCIJALNIH; ODREĐENI integral i Njutn–Lajbnic, primene — površina, zapremina, dužina luka; NESVOJSTVENI integrali i ispitivanje konvergencije). IV — DIFERENCIJALNE JEDNAČINE (prvog reda: razdvojene promenljive, homogene, linearne, Bernuli, egzaktne; jednačine VIŠEG REDA i linearne sa konstantnim koeficijentima; sistemi). USMENI ISPIT: precizne DEFINICIJE (granična vrednost funkcije u tački preko okolina, definicija izvoda i neprekidnosti) i DOKAZI teorema (o nizovima, srednjoj vrednosti, o integralima). TIPIČNI ZADACI SA KOLOKVIJUMA: lim (1+a/n)^(bn), lim (polinom)/(polinom), lim (ln x)/(x²+1); jednačina tangente na f u datoj tački; prvi izvodi datih funkcija; Maklorenov razvoj date funkcije; odredi parametar A tako da je f neprekidna na R; izračunaj date i nesvojstvene integrale; ispitaj tok i nacrtaj funkciju; reši diferencijalnu jednačinu. Kada učenik pošalje zadatak sa kolokvijuma ili sliku, reši ga POTPUNO korak po korak uz definiciju/teoremu koja se koristi, pa ponudi sličan za vežbu; izvode i integrale koristi iz tablice. " +
"OVAJ KURS (Matematička analiza 1, Informacioni inženjering) SADRŽI I UVODNI LINEARNO-ALGEBARSKI DEO (predavanja i vežbe 1–4): 1) MATRICE I DETERMINANTE — operacije, transponovanje, determinanta reda n i osobine (det(AB)=detA·detB, množenje vrste/kolone skalarom), rang, INVERZNA matrica preko adjungovane; 2) SISTEMI LINEARNIH JEDNAČINA — matrični oblik A·X=B, GAUSOV metod eliminacije, KRAMEROVO pravilo, Kroneker–Kapelijeva teorema, diskusija po parametru (određen/neodređen/kontradiktoran); 3) VEKTORI — intenzitet, pravac i smer, jedinični vektor, SKALARNI proizvod a·b (i ugao), VEKTORSKI proizvod a×b (i površina), MEŠOVITI proizvod a·(b×c) (i zapremina); 4) ANALITIČKA GEOMETRIJA U PROSTORU — jednačina PRAVE i RAVNI (Ax+By+Cz+D=0), vektor normale, prava kao presek dve ravni, RASTOJANJE tačke od prave/ravni, UGAO između pravih/ravni, paralelnost i normalnost, prodor prave kroz ravan. Reši i ove tipove do kraja korak po korak; matrice piši u uglastim zagradama." },

  { m: ["verovatnoca", "verovatnoća", "statistika", "slucajna promenljiva", "raspodela", "verovatnoca i statistika"], t:
"PREDMET: Verovatnoća i statistika. " +
"VEROVATNOĆA — obavezno znati: prostor elementarnih događaja, događaji i operacije nad njima; klasična, geometrijska i statistička definicija verovatnoće; osobine verovatnoće (sabiranje, komplement); uslovna verovatnoća P(A|B); nezavisnost događaja; formula množenja; formula totalne verovatnoće i Bajesova formula; kombinatorika kao alat (permutacije, varijacije, kombinacije). " +
"SLUČAJNE PROMENLJIVE: diskretne (zakon raspodele, funkcija raspodele F(x)) i neprekidne (gustina f(x), funkcija raspodele); numeričke karakteristike — matematičko očekivanje E(X), disperzija D(X)=σ², standardna devijacija, momenti; osobine očekivanja i disperzije. " +
"RASPODELE: diskretne — Bernulijeva, binomna, geometrijska, Poasonova, hipergeometrijska; neprekidne — uniformna, eksponencijalna, normalna (Gausova) N(μ,σ²) i standardizacija, veza sa centralnom graničnom teoremom; zakon velikih brojeva. " +
"STATISTIKA: populacija i uzorak; opisna statistika (aritmetička sredina, medijana, modus, uzoračka disperzija); tačkaste i intervalne procene (interval poverenja); testiranje hipoteza (nulta/alternativna, greške I i II vrste, z‑test, t‑test, χ² test); korelacija i linearna regresija. " +
"TIPOVI ZADATAKA: računanje verovatnoće događaja (klasična/kombinatorna), uslovna verovatnoća i nezavisnost, totalna verovatnoća i Bajes, sastavljanje zakona raspodele i računanje E(X) i D(X), rad sa binomnom/Poasonovom/normalnom raspodelom (standardizacija, tablice), intervali poverenja i testovi hipoteza. " +
"KOMPLETNOST: vladaš CELIM gradivom i svaki tip zadatka rešavaš do kraja, korak po korak (prvo intuicija pa formula, sa rešenim primerom). Verovatnoću piši kao P(A), uslovnu kao P(A|B), koristi puna imena (Bajesova formula, formula totalne verovatnoće, funkcija raspodele, funkcija gustine raspodele). Na platformi MathIA postoje i dokumenta za ovaj predmet (Skripta, Formule, Zadaci) — uputi učenika na njih." },

  { m: ["diskretna", "kombinatorika", "teorija grafova", "grafovi"], t:
"PREDMET: Diskretna matematika. " +
"Deo 1 — matematička logika (iskazi i iskazne formule, tablice istinitosti, tautologije, logičke ekvivalencije, kvantifikatori); skupovi, relacije (osobine, relacije ekvivalencije i poretka) i funkcije (injekcija, surjekcija, bijekcija, kompozicija); algebarske strukture (grupoid, polugrupa, monoid, grupa, prsten, polje); deljivost i kongruencije (Euklidov algoritam, NZD/NZS, modularna aritmetika, osnove teorije brojeva). " +
"Deo 2 — kombinatorika (pravila zbira i proizvoda, permutacije, varijacije, kombinacije sa i bez ponavljanja, binomni koeficijenti i binomna teorema, princip uključenja-isključenja, Dirihleov princip, rekurentne relacije i funkcije generatrise) i teorija grafova (pojam grafa, stepen čvora, putevi i konture, povezanost, Ojlerov i Hamiltonov put, stabla i razapinjuća stabla, bojenje grafa, planarni grafovi, matrica susedstva). " +
"TIPOVI ZADATAKA: dokazivanje logičkih ekvivalencija i tautologija, ispitivanje osobina relacija i funkcija, dokaz matematičkom indukcijom, kombinatorno prebrojavanje, uključenje-isključenje, rešavanje rekurentnih relacija, zadaci iz teorije grafova (Ojler/Hamilton, stabla, bojenje). " +
"KOMPLETNOST: vladaš CELIM gradivom i svaki tip zadatka rešavaš do kraja, korak po korak. Provere: kolokvijumi K1/K2 + usmeni. Na platformi MathIA postoje i dokumenta (Skripta, Formule, Zadaci) — uputi učenika na njih." },

  { m: ["uvod u elektroniku", "elektronika", "pojacavac", "pojacavaci"], t:
"PREDMET: Uvod u elektroniku. Teme: uvod i istorijat elektronike; poluprovodnici; dioda i primene (ispravljači); tranzistor (BJT, FET) kao pojačavač i prekidač; pojačavači (osnovne konfiguracije i primena pojačavača); povratna sprega; osnovna analiza kola. Laboratorija/merenja: rad sa osciloskopom (SIGLENT), generatorom signala, izvorom jednosmernog napona; lemljenje. Provere: dva kolokvijuma ili ispit. Klon vodi kroz analizu kola i lab merenja korak po korak." },

  { m: ["termodinamika", "prenos toplote", "toplotna"], t:
"PREDMET: Termodinamika / Osnovi termodinamike. Teme: osnovni pojmovi (sistem, stanje, veličine stanja); prvi zakon termodinamike (unutrašnja energija, rad, toplota); idealni gas i procesi (izohorski, izobarski, izotermski, adijabatski); drugi zakon i entropija; kružni procesi (Karnoov), toplotne mašine; osnovi prenosa toplote (provođenje, konvekcija, zračenje). Klon vodi kroz p-V dijagrame i proračune procesa." },

  { m: ["osnovi elektrotehnike", "oet", "teorija elektricnih kola", "elektricna kola", "teorija kola"], t:
"PREDMET: Osnovi elektrotehnike (spojeni Osnovi elektrotehnike 1 i 2; FTN Novi Sad, Katedra za teorijsku elektrotehniku — KTET; poznat i kao Teorija električnih kola). Vladaš CELIM gradivom, kroz sve tipove ispitnih zadataka (dva kolokvijuma: K1 elektrostatika + jednosmerna kola, K2 magnetika + kondenzatori/dielektrici). ELEKTROSTATIKA: jačina električnog polja $\\vec{E}$ i potencijal $V$ od raspodela naelektrisanja — tačkasto $Q$, podužna gustina $Q'$ na pravim i lučnim (kružnim, npr. 3/4 kruga) segmentima, površinska $\\sigma$, zapreminska $\\rho$; princip superpozicije i integracija doprinosa $d\\vec{E}$ po elementu naelektrisanja; polje u zadatoj tački (npr. centar strukture); Gausova teorema i fluks; provodnici u polju; kondenzatori (pločasti, cilindrični, sferni) i dielektrici (vezano naelektrisanje, $\\varepsilon_r$, više dielektrika u rednoj/paralelnoj vezi), energija polja $W=\\tfrac{1}{2}CU^2$, sile na pločice/naelektrisanje. JEDNOSMERNA KOLA: Omov zakon, Kirhofovi zakoni (I i II), redna i paralelna veza otpornika, delitelj napona i struje, metod kontura i čvorova, superpozicija, Tevenenova i Nortonova teorema (ekvivalentni generator), teorema o MAKSIMALNOJ SNAZI ($R_P=R_{Th}$, $P_{max}=\\dfrac{U_{Th}^2}{4R_{Th}}$), snaga i energija (Džulov zakon), realni izvori napona i struje. MAGNETIKA: magnetsko polje struje (Amperov zakon, Bio-Savarov zakon), $\\vec{B}$ i $\\vec{H}$, fluks $\\Phi$; magnetska kola (analogija sa strujnim kolom), torusno/prstenasto jezgro od jednog ili više materijala, nelinearni materijali i krive magnećenja $B\\!-\\!H$, ZASIĆENJE, ampernavojci $NI$, vazdušni procep; elektromagnetna indukcija (Faradejev zakon), samoindukcija i induktivnost kalema $L$, energija $W=\\tfrac{1}{2}LI^2$. METOD: prepoznaj tip (polje / kolo / magnetika), iskoristi simetriju i koordinatni sistem, integriši ili primeni teoremu korak po korak, proveri jedinice; UVEK nacrtaj skicu — kolo, raspored naelektrisanja ili magnetsko kolo — kao SVG, a sve izraze piši u LaTeX-u sa oznakama uobičajenim u elektrotehnici (imaginarna jedinica $j$)." +
"NAJČEŠĆI ZADACI NA KOLOKVIJUMIMA (FTN Novi Sad, Katedra za teorijsku elektrotehniku — KTET; I kolokvijum obično ima dva zadatka, svaki 25 poena, za prolaz treba više od 50% na svakom, traje 90 min): (1) ELEKTROSTATIKA — kondenzatori sa više slojeva dielektrika (npr. sferni ili pločasti kondenzator sa dva sloja različitih relativnih permitivnosti ε_r1 i ε_r2): odrediti izraz za kapacitivnost u opštim brojevima, maksimalni napon na koji sme da se priključi (iz dielektrične čvrstoće/probojne jačine polja E_č svakog sloja), i ukupno vezano (polarizaciono) naelektrisanje uz razdvojnu površ dva dielektrika; koristi Gausov zakon (∮D·dS = Q_slobodno), granične uslove (normalna komponenta vektora D neprekidna, tangencijalna komponenta E neprekidna), pa E = D/(ε0·ε_r) i U = ∫E·dl između elektroda; (2) KOLA VREMENSKI KONSTANTNIH (jednosmernih) STRUJA — mreže sa više generatora ems-a, strujnih izvora, otpornika i preklopnika: primenom teoreme superpozicije odrediti nepoznatu ems ili struju/napon (npr. promena U_AB pri prebacivanju preklopnika), i pokazivanja idealnih mernih instrumenata (idealni ampermetar = kratak spoj, idealni voltmetar = prekid grane); uz to Kirhofovi zakoni, Tevenenova/Nortonova teorema, delitelji napona i struje. METOD: ove tipove uvežbavaj svojim rečima korak po korak, sa jasnom skicom kola/polja, i pravi slične zadatke sa izmenjenim brojevima; ne prepisuj tuđa gotova rešenja doslovno. " +
"DODATNI TIPOVI SA ISPITA (FTN NS, KTET). I KOLOKVIJUM — elektrostatika: (a) naelektrisani tanki štapovi/savijeni izolacioni provodnici sa podužnom gustinom naelektrisanja, u kombinaciji sa tačkastim naelektrisanjem — odrediti vektor jačine električnog polja E u datoj tački (npr. centru O) superpozicijom doprinosa; (b) koaksijalni kabl (kondenzator) poluprečnika elektroda a i b, delimično ispunjen čvrstim dielektrikom (npr. do 3/5 zapremine, ε_r) — izvesti izraz za kapacitivnost u vertikalnom i horizontalnom položaju, izračunati je i naći razliku, plus ukupno vezano naelektrisanje; (c) pločasti (paralelni) kondenzator delimično ispunjen dielektrikom (deo vazduh, deo ε_r) — izvesti kapacitivnost, maksimalni napon (iz dielektrične čvrstoće), i raspodelu slobodnog naelektrisanja po delovima elektrode (npr. koliki deo površine nosi zadati udeo naelektrisanja). I KOLOKVIJUM — kola stalnih struja: Tevenenova teorema (uz određivanje ems Tevenenovog generatora metodom potencijala čvorova) za uslov maksimalne snage na grupi od n paralelnih otpornika — naći n i snage; promena snage generatora pri prebacivanju preklopnika. II KOLOKVIJUM — magnetika: (a) magnetska kola (tanko ili debelo torusno jezgro) od dva feromagnetska materijala sa idealizovanim/nelinearnim B–H karakteristikama, pobudni namotaj sa N zavojaka i strujom I — odrediti struju I za zadatu indukciju B u vazdušnom procepu, magnetsku energiju u pojedinim delovima, i režime rada (linearni/zasićenje) pri promeni struje; (b) beskonačno dugačak pravolinijski provodnik sa stalnom strujom I — odrediti vektor magnetske indukcije B u tački (Amperov/Bio-Savarov zakon). II KOLOKVIJUM — naizmenične (trofazne) struje: simetričan trofazni prijemnik (otpornici R + kondenzatori reaktanse X_C, ili zadat kompleksnom impedansom Z=R+jX, npr. Z=(20+j10) Ω) na simetričnoj trofaznoj mreži faznog napona U1=230 V — odrediti reaktanse kalemova za popravku faktora snage (cos φ), pokazivanja idealnih mernih instrumenata pre i posle, i skicirati fazorske dijagrame svih relevantnih napona i struja (veze zvezda/trougao). " +
"Klon vodi kroz proračun kola korak po korak (fazori, kompleksni račun)." },

  { m: ["elektromagnetika", "elektromagnetna", "maksvel"], t:
"PREDMET: Elektromagnetika. Teme: elektrostatika (Kulonov zakon, polje i potencijal, Gausov zakon, provodnici i dielektrici, kapacitivnost); stacionarno strujno polje; magnetostatika (Bio-Savar, Amperov zakon, magnetsko polje struja, materijali); elektromagnetna indukcija (Faradej, Lencov zakon, samo/međuindukcija); Maksvelove jednačine; elektromagnetni talasi (prostiranje, polarizacija). Klon vodi kroz vektorske proračune polja i primenu zakona." },

  { m: ["mehanika fluida", "fluid", "strujne masine", "hidraulika"], t:
"PREDMET: Mehanika fluida (Osnovi mehanike fluida 1/2). Teme: osobine fluida; statika fluida (pritisak, sila na površine, potisak); kinematika strujanja; jednačina kontinuiteta; Bernulijeva jednačina i primene; dinamika viskoznog fluida, gubici u cevima; strujne mašine; sistemi za transport i distribuciju fluida. Klon vodi kroz proračune protoka, pritisaka i gubitaka korak po korak." },

  { m: ["mehanika", "statika", "kinematika", "dinamika"], t:
"PREDMET: Mehanika (klasična — statika, kinematika i dinamika; FTN Novi Sad, Katedra za mehaniku, kurs E1). Vladaš CELIM gradivom i svim tipovima ispitnih zadataka (dva kolokvijuma: K1 tačka, K2 kruto telo). KINEMATIKA TAČKE: položaj, brzina i ubrzanje kod pravolinijskog i krivolinijskog kretanja, tangencijalno i normalno ubrzanje, kružno kretanje, horizontalni i kosi hitac (projektil), relativno kretanje. DINAMIKA TAČKE: Njutnovi zakoni, sile (težina, normalna reakcija, zategnutost užeta, trenje — statičko i kinetičko $F_{tr}=\\mu N$), kretanje po strmoj ravni i po krivini (centripetalna sila), sistemi tela povezanih užetom preko kotura. RAD, ENERGIJA I SNAGA: rad sile, teorema o kinetičkoj energiji $A=\\Delta E_k$, potencijalna energija (gravitaciona $mgh$ i elastična opruga $\\tfrac{1}{2}kx^2$), zakon održanja mehaničke energije, snaga $P=\\dfrac{dA}{dt}$. IMPULS I KOLIČINA KRETANJA: impuls sile, zakon održanja količine kretanja, SUDARI (elastični, neelastični, savršeno neelastični), kretanje centra mase. KRUTO TELO: moment inercije (disk, štap, obruč, sfera; Štajnerova teorema $J=J_C+md^2$), moment sile, osnovna jednačina rotacije $M=J\\alpha$, ugaona brzina i ubrzanje, kinetička energija rotacije $\\tfrac{1}{2}J\\omega^2$, KOTRLJANJE bez klizanja (veza $v=\\omega r$), održanje momenta količine kretanja, ravnoteža krutog tela (statika: $\\sum \\vec{F}=0$, $\\sum \\vec{M}=0$). METOD: prvo nacrtaj DIJAGRAM SLOBODNOG TELA sa svim silama (kao SVG), postavi ose, napiši jednačine ravnoteže ili kretanja, pa reši sistem korak po korak; drži se SI jedinica i piši sve u LaTeX-u. Za rotaciju uvek naznači osu i smer." +
"STATIKA: sile i momenti, sabiranje sila, spreg sila; ravnoteža krutog tela; oslonci i reakcije oslonaca (nosači, grede); rešetke; težište; trenje (klizno, kotrljanje). " +
"KINEMATIKA: kretanje tačke — položaj, brzina, ubrzanje; pravolinijsko i krivolinijsko kretanje (tangencijalno i normalno ubrzanje); kružno kretanje; kinematika krutog tela — translacija, rotacija oko ose, ravno (opšte) kretanje, trenutni pol. " +
"DINAMIKA: Njutnovi zakoni, dinamika materijalne tačke; rad, snaga i energija (zakon održanja energije); impuls i količina kretanja; moment količine kretanja; oscilacije (slobodne harmonijske, prigušene); dinamika krutog tela — moment inercije, rotacija, kotrljanje. " +
"DODATNO (obavezno znati): Štajnerova teorema (paralelni pomeraj ose za moment inercije); rad i energija pri rotaciji; sudari tela (elastični i neelastični, održanje impulsa i energije); centar masa složenih tela; d'Alamberov princip (dinamička ravnoteža); kod složenijih programa i Lagranževe jednačine i principi mehanike. " +
"TIPOVI ZADATAKA: ravnoteža sistema sila i reakcije oslonaca (grede, nosači), rešetke (metod čvorova/preseka); kinematika mehanizama i tela u ravnom kretanju (trenutni pol brzina); primena Njutnovih zakona i zakona održanja (energija/impuls/moment količine kretanja); zadaci sa trenjem (klizanje, kotrljanje, nagib); slobodne i prigušene oscilacije (period, frekvencija); moment inercije i dinamika rotacije. " +
"NAJČEŠĆI ZADACI NA KOLOKVIJUMIMA (FTN Novi Sad, predmet 'Mehanika (E1)', Katedra za Mehaniku — dva kolokvijuma). PRVI KOLOKVIJUM (kinematika i dinamika tačke): (1) pravolinijska kinematika sa konstantnim ili promenljivim ubrzanjem a(t) — npr. a(t)=At−Bt², naći v(t), x(t) i maksimalnu brzinu; zadaci susretanja dva tela (npr. automobil i kamion), zabijanje stuba maljem, vagon koji se ubrzava pa koči; (2) kosi i horizontalni hitac (projektil ispaljen iz topa ka litici, paket bačen horizontalno) — komponente brzine, domet i visina, brzina neposredno pre udara, provera da li pogađa cilj; (3) rad–energija sa oprugom i trenjem — telo lansirano sabijenom oprugom po glatkoj ili hrapavoj podlozi, kretanje po unutrašnjosti cilindra ili četvrtine kruga, naći brzinu u zadatoj tački i maksimalno skraćenje opruge, uz zakon o promeni kinetičke energije i rad sile trenja. DRUGI KOLOKVIJUM (kruto telo, oscilacije, gravitacija, sistemi tela): (1) rotaciona kinematika i dinamika diska/kotura — konopac namotan na disk, tangencijalno ubrzanje a(t)=At, ugaono ubrzanje ε(t) i ugaona brzina ω(t), moment inercije, disk koji se zavrti povlačenjem konopca; (2) statika grede — homogena greda AB u ravnoteži, nepokretni zglob A i uže BC pod uglom, okačen teret; naći silu zatezanja užeta i reakcije zgloba iz ∑Fx=0, ∑Fy=0, ∑M=0; (3) impuls i sudari tela na glatkoj podlozi (održanje količine kretanja, elastični/neelastični sudar); (4) kružno kretanje i gravitacija — satelit u kružnoj orbiti na visini h, orbitalna brzina i period; (5) prosto harmonijsko oscilovanje — telo na opruzi, ukupna mehanička energija oscilatora, amplituda, period i frekvencija; (6) sistemi tela sa koturom i protivtegom uz trenje — kutija na stolu vezana preko kotura sa tegom, podizanje tereta protivtegom. METOD: ove tipove uvežbavaj sa studentom svojim rečima, korak po korak, pravi slične zadatke sa izmenjenim brojevima za vežbu; NE prepisuj tuđa gotova rešenja doslovno. " +
"PRODUBLJENO — KINEMATIKA TAČKE (uvežbavaj sve tipove): načini zadavanja kretanja (prirodni — put s(t) po putanji; vektorski — r(t); Dekartov — x(t), y(t), z(t)); brzina v=ds/dt i ubrzanje a=dv/dt; komponente ubrzanja — tangencijalno a_t=dv/dt i normalno (centripetalno) a_n=v²/R, ukupno a=√(a_t²+a_n²), poluprečnik krivine putanje R; pravolinijsko kretanje sa konstantnim i promenljivim ubrzanjem a(t), a(v), a(s) (integracija do v(t) i x(t)); krivolinijsko kretanje u ravni (putanja, kosi i horizontalni hitac); kružno kretanje tačke — ugao φ(t), ugaona brzina ω=dφ/dt, ugaono ubrzanje ε=dω/dt, obimna brzina v=Rω, a_t=Rε, a_n=Rω²; složeno (relativno) kretanje tačke — apsolutno, prenosno i relativno kretanje, Koriolisovo ubrzanje. PRODUBLJENO — STATIKA (uvežbavaj sve tipove): rezultanta konkurentnih sila, moment sile za tačku i za osu, spreg sila i redukcija sistema sila na tačku (glavni vektor i glavni moment); uslovi ravnoteže krutog tela — ravanski (∑Fx=0, ∑Fy=0, ∑M=0) i prostorni (šest jednačina); oslonci i reakcije (pokretni i nepokretni oslonac, uklještenje/konzola, uže, štap), proste grede i konzole; GREDNI NOSAČI (linijski nosači) — odrediti reakcije oslonaca i nacrtati dijagrame unutrašnjih (presečnih) sila: aksijalne/normalne sile N, transverzalne/smičuće sile T i momenta savijanja M, analizom po poljima i karakterističnim tačkama, za opterećenja koncentrisanim silama F, spregovima (momentima) M i kontinualnim (podeljenim) opterećenjem q [kN/m], uz kose sile pod uglom α; koristi diferencijalne veze dT/dx=−q i dM/dx=T (ekstrem momenta gde je T=0), i uslov da moment na slobodnom/zglobnom kraju iščezava; rešetke — metod čvorova i metod preseka (Riterov), određivanje sila u štapovima uz oznaku zategnut/pritisnut, nulti štapovi; trenje — klizno (Kulonov zakon, koeficijent μ, ugao trenja), ravnoteža na strmoj ravni i sa klinom, trenje užeta na cilindru (Ojlerova formula T2=T1·e^{μα}), kotrljanje; težište linije, površine i tela, složena tela, Papus–Guldinove teoreme. Reši svaki zadatak do kraja korak po korak, uvek sa skicom oslobođenog tela i jasno postavljenim jednačinama; pravi slične zadatke za vežbu, ne prepisuj tuđa rešenja. " +
"KOMPLETNOST: vladaš CELIM gradivom ovog predmeta i svaki tip zadatka rešavaš do kraja. Objašnjavaj sa skicom slobodnog tela (sve sile), jasno razdvoji poznato/nepoznato, postavi jednačine ravnoteže ili kretanja, pa reši korak po korak; jedinice piši u zagradama, npr. (N·m). Sve formule i izraze piši ispravnim LaTeX-om u $...$ (aplikacija ih lepo iscrtava). Na platformi MathIA postoje i zvanična dokumenta za ovaj predmet — Skripta (teorija), Formule (podsetnik) i Zadaci (rešeni) — pa po potrebi uputi učenika na njih." },
  { m: ["os-mat-5","osn-mat-5","matematika 5"], t: "PREDMET: Matematika, 5. razred osnovne škole. Gradivo (zvanični program): prirodni brojevi i deljivost; osnovni pojmovi geometrije; ugao; razlomci i decimalni brojevi (operacije); osna simetrija; površina i zapremina. Metod: objasni pojam rečima, pokaži na primeru, pa vežbaj korak po korak; primereno uzrastu 11 godina." },
  { m: ["os-mat-6","osn-mat-6","matematika 6"], t: "PREDMET: Matematika, 6. razred osnovne škole. Gradivo: celi brojevi; racionalni brojevi (operacije, razlomci); trougao (uglovi, podudarnost); četvorougao; površina trougla i četvorougla; procenti. Metod: strpljivo, korak po korak, sa slikama i primerima." },
  { m: ["os-mat-7","osn-mat-7","matematika 7"], t: "PREDMET: Matematika, 7. razred osnovne škole. Gradivo: realni brojevi; Pitagorina teorema; celi i racionalni algebarski izrazi (polinomi, kvadrat binoma); mnogougao; direktna i obrnuta proporcionalnost i grafičko predstavljanje; krug (obim, površina); sličnost trouglova. Metod: korak po korak, uz crteže." },
  { m: ["os-mat-8","osn-mat-8","matematika 8"], t: "PREDMET: Matematika, 8. razred osnovne škole. Gradivo: tačka, prava i ravan (geometrija u prostoru); linearne jednačine i nejednačine s jednom nepoznatom; prizma; piramida; linearna funkcija; sistemi linearnih jednačina s dve nepoznate; valjak, kupa i lopta (obrtna tela); obrada podataka. Priprema za malu maturu." },
  { m: ["sr-mat-1","matematika 1. razred","srednja matematika 1"], t: "PREDMET: Matematika, 1. razred srednje škole. Gradivo: logika i skupovi; realni brojevi; proporcionalnost (proporcije, procenti); uvod u geometriju i podudarnost; racionalni algebarski izrazi (polinomi); linearna funkcija, jednačine i nejednačine; trigonometrija pravouglog trougla." },
  { m: ["sr-mat-2","matematika 2. razred","srednja matematika 2"], t: "PREDMET: Matematika, 2. razred srednje škole. Gradivo: stepenovanje i korenovanje; kvadratna jednačina i kvadratna funkcija; eksponencijalna i logaritamska funkcija (jednačine i nejednačine); trigonometrijske funkcije; sličnost." },
  { m: ["sr-mat-3","matematika 3. razred","srednja matematika 3"], t: "PREDMET: Matematika, 3. razred srednje škole. Gradivo: stereometrija (poliedri i obrtna tela); vektori; analitička geometrija u ravni (prava, kružnica, konusni preseci); nizovi i matematička indukcija (aritmetički i geometrijski niz); kompleksni brojevi (trigonometrijski oblik)." },
  { m: ["sr-mat-4","matematika 4. razred","srednja matematika 4"], t: "PREDMET: Matematika, 4. razred srednje škole. Gradivo: granična vrednost i neprekidnost funkcije; izvod i primene (ekstremumi, tok funkcije); ispitivanje funkcija; integral (neodređeni i određeni, površina); kombinatorika; verovatnoća i statistika. Priprema za maturu i prijemni." },
  { m: ["os-fiz-6","osn-fiz-6","fizika 6"], t: "PREDMET: Fizika, 6. razred osnovne škole. Gradivo: uvod (fizika kao nauka, fizičke veličine i merenje); kretanje (brzina); sila; masa i gustina; ravnoteža i pritisak. Metod: pojava iz svakodnevice → objašnjenje → formula → primer, primereno uzrastu." },
  { m: ["os-fiz-7","osn-fiz-7","fizika 7"], t: "PREDMET: Fizika, 7. razred osnovne škole. Gradivo: sila i kretanje (Njutnovi zakoni); kretanje pod dejstvom sile teže i sile trenja; ravnoteža tela (poluga, moment sile); mehanički rad, energija i snaga; toplotne pojave (temperatura, toplota)." },
  { m: ["os-fiz-8","osn-fiz-8","fizika 8"], t: "PREDMET: Fizika, 8. razred osnovne škole. Gradivo: oscilatorno i talasno kretanje (zvuk); svetlosne pojave (optika, ogledala, sočiva); elektrostatika; električna struja (Omov zakon, kola); magnetno polje; elementi atomske i nuklearne fizike." },
  { m: ["sr-fiz-1","fizika 1. razred","srednja fizika 1"], t: "PREDMET: Fizika, 1. razred srednje škole. Gradivo: uvod i merenje; kinematika; dinamika (Njutnovi zakoni); zakoni održanja (impuls, rad, energija, snaga); gravitacija (Keplerovi zakoni); mehanika fluida; oscilacije i talasi." },
  { m: ["sr-fiz-2","fizika 2. razred","srednja fizika 2"], t: "PREDMET: Fizika, 2. razred srednje škole. Gradivo: molekularno-kinetička teorija gasova; termodinamika (toplota, unutrašnja energija, zakoni); elektrostatika (električno polje, potencijal, kondenzatori); stalna (jednosmerna) električna struja." },
  { m: ["sr-fiz-3","fizika 3. razred","srednja fizika 3"], t: "PREDMET: Fizika, 3. razred srednje škole. Gradivo: magnetno polje; elektromagnetna indukcija; naizmenična struja; elektromagnetni talasi; optika (geometrijska i talasna)." },
  { m: ["sr-fiz-4","fizika 4. razred","srednja fizika 4"], t: "PREDMET: Fizika, 4. razred srednje škole. Gradivo: talasna (fizička) optika; osnovi kvantne fizike (fotoelektrični efekat, dualizam); atomska fizika (Borov model, spektri); nuklearna fizika i elementarne čestice; elementi teorije relativnosti." },
  { m: ["mala-matura","zavrsni ispit","mala matura"], t: "PREDMET: Priprema za malu maturu (završni ispit iz matematike, 8. razred). Test od 20 zadataka (osnovni, srednji i napredni nivo). SVE OBLASTI po obrazovnim standardima, sa celim gradivom osnovne škole (5–8): 1) BROJEVI I OPERACIJE: prirodni, celi, racionalni i realni brojevi; deljivost (prosti brojevi, NZD, NZS); razlomci i decimalni brojevi; procenti; razmere i proporcije; stepeni sa celobrojnim izložiocem; kvadratni koren; zaokrugljivanje i procena. 2) ALGEBRA I FUNKCIJE: algebarski izrazi i polinomi (kvadrat binoma, razlika kvadrata, rastavljanje na činioce); linearne jednačine i nejednačine; sistemi linearnih jednačina; linearna funkcija (grafik, nula, rast/opadanje); direktna i obrnuta proporcionalnost. 3) GEOMETRIJA: uglovi (na paralelnim pravama, u trouglu i mnogouglu); trougao (podudarnost, Pitagorina teorema); četvorouglovi; pravilni mnogougao; krug i kružnica (obim, površina, centralni i periferijski ugao); sličnost trouglova; geometrijske transformacije (osna i centralna simetrija, translacija, rotacija). 4) MERENJE: dužina, površina, zapremina, masa, vreme; obimi i površine ravnih figura; POVRŠINA I ZAPREMINA TELA — prizma, piramida, valjak, kupa i lopta. 5) OBRADA PODATAKA: tabele i dijagrami; aritmetička sredina i medijana; osnovna verovatnoća. Metod: prepoznaj tip zadatka → strategija → rešen primer korak po korak; vežbanje po nivoima; sve piši matematički korektno (LaTeX), sa jedinicama." },
  { m: ["prijemni-visa","priprema-visa","visa skola"], t: "PREDMET: Priprema za prijemni ispit za više/visoke strukovne škole (matematika). Oblasti: osnovne operacije, procenti i proporcije; algebarski izrazi (polinomi, racionalni izrazi); linearne i kvadratne jednačine, nejednačine i funkcije; sistemi jednačina; stepeni i koreni; logaritmi i eksponencijalne funkcije; trigonometrija; planimetrija (obimi i površine). Metod: tipovi zadataka sa prijemnih, korak po korak." },
  { m: ["prijemni-matematika","prijemni-ftn","prijemni fakultet","priprema-fakultet"], t: "PREDMET: Priprema za prijemni ispit iz matematike za fakultete i visoke škole (FTN Novi Sad; ETF, Mašinski, Građevinski, PMF i Matematički u Beogradu; Elektronski, Mašinski i PMF u Nišu; i drugi tehnički fakulteti). SVE OBLASTI: 1) osnovne logičke operacije, skupovi i pojam funkcije; 2) brojevi: prirodni, celi, racionalni, iracionalni, realni i KOMPLEKSNI; 3) proporcionalnost i procenti; 4) racionalni algebarski izrazi i POLINOMI; 5) linearna funkcija, linearne jednačine, nejednačine i sistemi; 6) stepenovanje i korenovanje; 7) kvadratna funkcija, kvadratne jednačine i nejednačine; 8) algebarske i IRACIONALNE jednačine i nejednačine; 9) EKSPONENCIJALNE i LOGARITAMSKE jednačine, nejednačine i funkcije; 10) TRIGONOMETRIJA (funkcije, identiteti, jednačine); 11) matematička INDUKCIJA i NIZOVI (aritmetička i geometrijska progresija), granična vrednost; 12) KOMBINATORIKA i BINOMNI obrazac; 13) PLANIMETRIJA i ANALITIČKA GEOMETRIJA (prava, kružnica, elipsa, parabola, hiperbola); 14) STEREOMETRIJA (površine i zapremine tela); 15) (za ETF, PMF i Matematički) granična vrednost, IZVOD funkcije i primene. FTN varijante prijemnog: 'Matematika' (elektrotehnika i računarstvo, mehatronika, saobraćaj, geodezija, energetika); 'MATEMATIKA SA LOGIKOM' (mašinstvo, industrijsko inženjerstvo i menadžment) — uz gradivo, i iskazna logika, logičke zagonetke, nizovi i šeme; 'MATEMATIKA SA PROVEROM SKLONOSTI' (građevinarstvo, grafičko inženjerstvo i dizajn, inženjerstvo zaštite) — uz gradivo, i prostorna vizualizacija i sklonost ka struci. Metod: rešeni zadaci sa prijemnih (tip → postupak → rešenje), sve u LaTeX-u, sa proverom rezultata." },
  { m: ["prijemni-logika","test logike","provera sklonosti","test sklonosti fakultet","logika prijemni","matematika sa logikom"], t: "PREDMET: Priprema za PROVERU SKLONOSTI i TEST LOGIKE na prijemnom (kao na tehničkim fakultetima — FTN i drugi). Pitanja SA PONUĐENIM ODGOVORIMA. Tipovi: iskazna logika (tačno/netačno, implikacija, negacija, konjunkcija/disjunkcija); logičke zagonetke i zaključivanje; NIZOVI brojeva i figura (naći sledeći član/pravilo); analogije; PROSTORNA VIZUALIZACIJA (rotacije tela, mreže kocke/prizme, preseci); kombinatorne i procentne zagonetke; brzo računanje i procena. Metod: pitanje → 4 ponuđena odgovora → tačan odgovor + kratko objašnjenje zašto, i kako eliminisati netačne opcije." },

];

export function scopeFor(sub) {
  const s = norm(sub);
  if (!s) return "";
  for (const e of MAP) {
    if (e.m.some(function (k) { return s.includes(norm(k)); })) return e.t;
  }
  return "";
}
