// ============================================================
//  lib/klon-znanje.js — mapa GRADIVA po predmetu za klona.
//  Daje kratak "scope" (spisak tema) koji se dodaje u sistemski prompt,
//  da klon zna ŠTA sve ulazi u predmet i vodi učenika kroz te teme.
//  Sadrži samo ČINJENIČNE teme/strukturu (ne prepisuje tuđe materijale).
//  Izvori: otvoreni repozitorijumi FTN Novi Sad (ACS, Katedra za matematiku).
// ============================================================

function norm(s) {
  return String(s || "").toLowerCase()
    .replace(/[čćĉ]/g, "c").replace(/[šŝ]/g, "s").replace(/[žŵ]/g, "z").replace(/đ/g, "dj")
    .replace(/[^a-z0-9 ]/g, " ").replace(/\s+/g, " ").trim();
}

// Svaka stavka: ključne reči za prepoznavanje (m) + tekst gradiva (t).
const MAP = [
  { m: ["analiza2", "analiza 2", "matematicka analiza 2"], t:
"PREDMET: Matematička analiza 2. Vladaš CELIM gradivom: brojni redovi (kriterijumi konvergencije — poredbeni, količnički/D'Alamber, koreni/Koši, integralni, Lajbnic za alternativne), funkcionalni i stepeni redovi (poluprečnik i interval konvergencije, Tejlorov i Maklorenov razvoj), Furijeovi redovi; funkcije više promenljivih (parcijalni izvodi, gradijent, totalni diferencijal, izvod složene funkcije, lokalni i uslovni ekstremi — Lagranžovi množioci, Heseova determinanta); višestruki integrali (dvojni i trojni, smena u polarne/cilindrične/sferne koordinate, primene — površina, zapremina, masa, težište); vektorska analiza i teorija polja (gradijent, divergencija, rotor, krivolinijski i površinski integrali, Grinova, Stoksova i Gaus–Ostrogradski teorema). TIPOVI ZADATAKA: ispitivanje konvergencije redova, poluprečnik konvergencije, parcijalni izvodi i ekstremi, dvojni/trojni integrali sa smenom, krivolinijski/površinski integrali, primena teorema polja. Objašnjavaj korak po korak (prvo intuicija, pa formula), formule ispravnim LaTeX-om; svaki zadatak reši do kraja. Na platformi postoje Skripta, Formule i Zadaci za ovaj predmet." },

  { m: ["kompleksna analiza", "kompleksna", "kompleksne funkcije"], t:
"PREDMET: Kompleksna analiza. Gradivo: kompleksni brojevi i funkcije kompleksne promenljive, Ojlerov oblik z = r·e^{iφ}; analitičke (holomorfne) funkcije i Koši–Rimanovi uslovi, harmonijske funkcije; elementarne funkcije kompleksne promenljive (exp, log, stepen, trig); konformna preslikavanja; integracija u kompleksnoj ravni — Košijeva teorema i Košijeva integralna formula; redovi (Tejlorov i Loranov), singulariteti i klasifikacija polova; teorema o reziduumima i primena na realne integrale. TIPOVI ZADATAKA: provera analitičnosti (Koši–Riman), računanje reziduuma i integrala po konturi, Loranov razvoj, primena Košijeve formule. Imaginarnu jedinicu piši i; sve formule LaTeX-om; reši do kraja korak po korak. Postoje Skripta, Formule i Zadaci." },

  { m: ["operaciona istrazivanja", "operaciona", "linearno programiranje", "simpleks"], t:
"PREDMET: Operaciona istraživanja. Gradivo: modeliranje odlučivanja; linearno programiranje (funkcija cilja i ograničenja, dopustiva oblast, grafička metoda za 2 promenljive); simpleks metoda (dopunske promenljive, simpleks tabela, pivotiranje, kriterijum optimuma, dualnost); transportni i problem raspoređivanja (severozapadni ugao, VAM, potencijali); mrežno planiranje CPM/PERT (kritičan put, rezerve, PERT očekivano vreme t_e=(a+4m+b)/6); osnove teorije igara i modela zaliha. TIPOVI ZADATAKA: postavljanje LP modela, grafičko i simpleks rešavanje, transportni problem, kritičan put i vremena aktivnosti. Reši do kraja korak po korak, tabele daj uredno. Postoje Skripta, Formule i Zadaci." },

  { m: ["linearna algebra"], t:
"PREDMET: Linearna algebra. Gradivo: matrice i operacije, determinante (osobine, razvoj), inverzna matrica i rang; sistemi linearnih jednačina (Gausov postupak, Kramerovo pravilo, Kroneker–Kapelijeva teorema); vektorski prostori i potprostori, linearna zavisnost, baza i dimenzija; linearne transformacije i matrična reprezentacija; sopstvene (karakteristične) vrednosti i vektori, dijagonalizacija; skalarni proizvod, ortogonalnost, Gram–Šmit. Reši do kraja korak po korak; formule LaTeX-om. (Materijali za ovaj predmet su zajednički sa Algebrom.)" },

  { m: ["sistemisigna", "sistemi i signali", "signal", "signali"], t:
"PREDMET: Signali i sistemi. Gradivo: klasifikacija signala (kontinualni/diskretni, periodični, energetski/snažni), osnovni signali (impuls, step, eksponencijalni); sistemi i osobine (linearnost, vremenska nepromenljivost — LTI, kauzalnost, stabilnost); impulsni odziv i konvolucija; Furijeov red i Furijeova transformacija; Laplasova i Z transformacija; prenosna funkcija H(s), polovi i nule, frekventni odziv (Bodeovi dijagrami). TIPOVI ZADATAKA: provera LTI osobina, konvolucija, Laplas/Furije transformacije, analiza stabilnosti preko polova, prenosna funkcija. Reši do kraja; formule LaTeX-om. Postoje Skripta, Formule i Zadaci." },

  { m: ["pojacavaci", "pojacavac", "elektronika pojacavaci"], t:
"PREDMET: Elektronika — pojačavači. Gradivo: radna tačka i polarizacija tranzistora (BJT, FET), stabilizacija radne tačke; modeli za male signale; naponsko i strujno pojačanje, ulazna i izlazna otpornost; osnovne konfiguracije (zajednički emiter/sors, kolektor/drejn, baza/gejt); negativna povratna sprega (uticaj na pojačanje, opseg i stabilnost, A_f=A/(1+Aβ)); frekventni odziv i propusni opseg; višestepeni i operacioni pojačavači. TIPOVI ZADATAKA: proračun radne tačke, pojačanje u dB (20log), povratna sprega, kaskada. Crtaj kolo po potrebi; reši do kraja. Postoje Skripta, Formule i Zadaci." },

  { m: ["digitalna elektronika", "digitalna", "logicka kola"], t:
"PREDMET: Digitalna elektronika. Gradivo: brojni sistemi i kodovi; logičke kapije i Bulova algebra (aksiomi, De Morgan), minimizacija (Karnoove mape, Quine–McCluskey); kombinacione mreže (dekoderi, koderi, multiplekseri, sabirači, komparatori); sekvencijalne mreže (leč i flip-flopovi D/JK/T, registri, brojači, sinhroni/asinhroni); konačni automati; osnove logičkih familija (TTL, CMOS). TIPOVI ZADATAKA: konverzije brojnih sistema, minimizacija logičke funkcije, projektovanje kombinacione mreže, analiza brojača/registara. Reši do kraja korak po korak. Postoje Skripta, Formule i Zadaci." },

  { m: ["impulsna elektronika", "impulsna"], t:
"PREDMET: Impulsna elektronika. Gradivo: impulsni signali i parametri (amplituda, trajanje, front, faktor ispune); RC kola kao oblikovači (integrator, diferencijator, τ=RC); diodni oblikovači (odsecanje, fiksiranje nivoa); komparatori i okidna kola (Šmitov triger); multivibratori (astabilni, monostabilni, bistabilni); tajmer 555 (astabilni T≈0,7(R1+2R2)C, monostabilni t≈1,1RC); generatori talasnih oblika. TIPOVI ZADATAKA: proračun τ, perioda i frekvencije multivibratora, 555 kola, oblikovanje signala. Reši do kraja. Postoje Skripta, Formule i Zadaci." },

  { m: ["energetskael", "energetska elektronika"], t:
"PREDMET: Energetska elektronika. Gradivo: poluprovodnički prekidači snage (dioda, tiristor, GTO, MOSFET, IGBT); ispravljači (jednofazni i trofazni, neupravljani i upravljani — ugao paljenja α, U_dc=U_dc0·cosα); DC-DC pretvarači (buck U_iz=D·U_ul, boost U_iz=U_ul/(1−D), buck-boost); invertori (DC-AC) i PWM modulacija; naizmenični regulatori; primene (pogoni, napajanja, obnovljivi izvori). TIPOVI ZADATAKA: srednja vrednost ispravljača, faktor ispune, buck/boost izlaz, upravljani ispravljač. Reši do kraja. Postoje Skripta, Formule i Zadaci." },

  { m: ["elektricnema", "elektricne masine", "transformator", "asinhroni", "sinhroni motor"], t:
"PREDMET: Električne mašine. Gradivo: transformatori (princip, prenosni odnos k=N1/N2=U1/U2, ekvivalentna šema, gubici u bakru i gvožđu, stepen korisnosti η=P2/P1, trofazni transformatori); asinhrone (indukcione) mašine (obrtno polje, sinhrona brzina n_s=60f/p, klizanje s=(n_s−n)/n_s, moment i karakteristika); sinhrone mašine (generator, frekvencija f=pn/60, pobuda); mašine jednosmerne struje (EMS E=kΦn, moment M=kΦI, motori i generatori); specijalne mašine (koračni θ=360/N, servo) i osnove električnih pogona. TIPOVI ZADATAKA: prenosni odnos i η transformatora, klizanje i brzina asinhrone, frekvencija sinhrone, EMS i moment jednosmerne. Reši do kraja. Postoje Skripta, Formule i Zadaci." },

  { m: ["eds", "elektrodistributivni", "distributivni sistemi", "distributivne mreze"], t:
"PREDMET: Elektrodistributivni sistemi. Gradivo: struktura i naponski nivoi distributivnih mreža (SN i NN), radijalne i prstenaste mreže; proračun tokova snaga, padovi napona ΔU=I(R·cosφ+X·sinφ) i gubici P=3I²R; kvalitet napona; kompenzacija reaktivne snage (kondenzatorske baterije, popravka cosφ); zaštita i pouzdanost distributivne mreže; priključci i bilansi. TIPOVI ZADATAKA: pad napona i gubici u vodu, dimenzionisanje, kompenzacija cosφ. Reši do kraja korak po korak. Postoje Skripta, Formule i Zadaci." },

  { m: ["elektroenerg", "elektroenergetski pretvaraci", "pretvaraci"], t:
"PREDMET: Elektroenergetski pretvarači. Gradivo: pretvarači u elektroenergetskom sistemu; upravljani ispravljači (tiristorski mostovi, ugao paljenja α, srednja vrednost U_dc=U_dc0·cosα, invertorski režim za α>90°); invertori i AC-AC pretvarači; HVDC prenos; primene u pogonima i mrežama, harmonici i filtriranje. TIPOVI ZADATAKA: srednji napon upravljanog ispravljača, ugao paljenja, režimi rada. Reši do kraja. Postoje Skripta, Formule i Zadaci." },

  { m: ["merenjanev", "merenja neelektricnih", "neelektricnih velicina"], t:
"PREDMET: Merenja neelektričnih veličina. Gradivo: senzori i merni pretvarači (temperatura — Pt100 R_t=R0(1+αΔT), termopar; pritisak; pomeraj i sila — otpornički, kapacitivni, induktivni, tenzometri; protok; nivo); statička i dinamička karakteristika, osetljivost S=Δizlaz/Δulaz, linearnost, histerezis; kondicioniranje signala i merni mostovi; A/D konverzija. TIPOVI ZADATAKA: osetljivost senzora, Pt100 proračun, most, linearizacija. Reši do kraja. Postoje Skripta, Formule i Zadaci." },

  { m: ["elektricna merenja", "merni instrumenti", "vitstonov most"], t:
"PREDMET: Električna merenja. Gradivo: merni instrumenti (analogni i digitalni), greške merenja (apsolutna, relativna δ=Δx/x·100%, klasa tačnosti); merenje napona, struje i otpornosti; proširenje opsega (shunt R_s=R_A/(n−1), predotpor); mostne metode (Vitstonov most u ravnoteži R1·R4=R2·R3), kompenzacione metode; merenje snage i energije; osciloskop. TIPOVI ZADATAKA: relativna greška, Vitstonov most, shunt/predotpor. Reši do kraja. Postoje Skripta, Formule i Zadaci." },

  { m: ["materijali", "materijali u elektrotehnici", "materijali et"], t:
"PREDMET: Materijali u elektrotehnici. Gradivo: provodnici (otpornost R=ρl/S, provodnost σ=1/ρ, temperaturna zavisnost R_t=R0(1+αΔT), superprovodnost); poluprovodnici (sopstveni i primesni, PN spoj); dielektrici (permitivnost, polarizacija, dielektrična čvrstoća/proboj, kapacitivnost C=ε0εrA/d, gubici); magnetni materijali (permeabilnost, histerezisna petlja, meki i tvrdi magnetici). TIPOVI ZADATAKA: otpornost provodnika, temperaturna promena, kapacitivnost sa dielektrikom. Reši do kraja. Postoje Skripta, Formule i Zadaci." },

  { m: ["kola", "teorija elektricnih kola", "teorija kola", "elektricna kola"], t:
"PREDMET: Teorija električnih kola. Gradivo: elementi kola (R, L, C, izvori) i osnovni zakoni (Om, Kirhofovi zakoni); metode analize (metod kontura i čvorova, superpozicija, Tevenenova i Nortonova teorema, teorema o maksimalnoj snazi); prelazni procesi u RC/RL/RLC kolima; naizmenična kola u kompleksnom domenu (fazori, impedansa Z=R+jX, admitansa, snage — aktivna/reaktivna/prividna, rezonansa); trofazni sistemi; četvoropoli. TIPOVI ZADATAKA: Tevenen/Norton, čvorna/konturna analiza, prelazni proces, fazorski proračun, rezonansa. Reši do kraja. Postoje Skripta, Formule i Zadaci." },

  { m: ["osnovielektr"], t:
"PREDMET: Osnovi elektrotehnike (1 i 2). OET 1 — jednosmerne struje (Om, Kirhof, analiza mreža, Tevenen/Norton, snaga) i električno polje (Kulon, potencijal, kondenzatori, energija). OET 2 — magnetsko polje i elektromagnetna indukcija (Faradej, induktivnost) i naizmenične struje (fazori, reaktanse X_L=ωL i X_C=1/ωC, impedansa, snage, rezonansa f0=1/(2π√(LC)), prelazni procesi τ=RC). TIPOVI ZADATAKA: analiza kola, delitelji, kondenzator, reaktansa/impedansa, rezonansa. Reši do kraja korak po korak. Postoje Skripta, Formule i Zadaci." },

  { m: ["elektromagne", "elektromagnetika 2", "maksvelove"], t:
"PREDMET: Elektromagnetika. Gradivo: elektrostatika (Kulonov zakon, jačina polja i potencijal, Gausov zakon ∮E·dS=Q/ε, provodnici i dielektrici, kapacitivnost); stacionarno strujno polje; magnetostatika (Bio–Savar, Amperov zakon ∮H·dl=I, sila na naelektrisanje i provodnik); elektromagnetna indukcija (Faradej, Lencov zakon, samo/međuindukcija); Maksvelove jednačine; elektromagnetni talasi (prostiranje, brzina c=1/√(με), polarizacija). TIPOVI ZADATAKA: polje i potencijal, Gausov zakon, sila na provodnik, indukovani napon. Reši do kraja; vektorski proračuni. Postoje Skripta, Formule i Zadaci." },

  { m: ["nacrtna", "nacrtna geometrija"], t:
"PREDMET: Nacrtna geometrija. Gradivo: metode projektovanja (ortogonalna/Mongeova, aksonometrija, kotirana, perspektiva); tačka, prava i ravan u projekcijama i njihovi odnosi (presek, paralelnost, normalnost); prava veličina duži i ugla; rotacija i obaranje ravni; prodori i preseci tela (prizma, piramida, valjak, kupa, lopta); razvijanje površi. TIPOVI ZADATAKA: konstrukcije u projekcijama, prava veličina, presek tela ravni, prodori. Objašnjavaj sa jasnom konstrukcijom korak po korak; koristi SVG skice kad pomažu." },

  { m: ["web programiranje", "web", "html", "css", "javascript", "frontend"], t:
"PREDMET: Web programiranje. Gradivo: HTML (struktura, semantika, forme), CSS (selektori, box-model, flexbox, grid, responsivnost), JavaScript (tipovi, funkcije, DOM, događaji, asinhrono — fetch/Promise/async-await), osnove HTTP-a i REST API-ja; front-end okviri (npr. React — komponente, stanje, props) i osnovni back-end (Node/Express); rad sa JSON-om; osnove bezbednosti i deploy. TIPOVI ZADATAKA: napravi stranicu/komponentu, obradi formu i događaje, pozovi API i prikaži podatke, responsivni raspored. Daj kompletan, ispravan kod u blokovima sa oznakom jezika; objasni pristup." },

  { m: ["hci", "interakcija covek racunar", "korisnicko iskustvo", "ux"], t:
"PREDMET: Interakcija čovek–računar (HCI). Gradivo: principi upotrebljivosti (Nilsenove heuristike), dizajn interfejsa i korisničko iskustvo (UX), mentalni modeli, afordanse; proces dizajna usmeren na korisnika (istraživanje, persone, žičani modeli, prototipovi, iterativno testiranje upotrebljivosti); pristupačnost; evaluacija (heuristička, kognitivni prolaz, A/B). TIPOVI ZADATAKA: heuristička evaluacija ekrana, predlog poboljšanja UX, plan testiranja upotrebljivosti, žični model. Objašnjavaj jasno i praktično, sa konkretnim primerima." },

  { m: ["programski prevodioci", "prevodioci", "kompajler", "kompajleri"], t:
"PREDMET: Programski prevodioci (kompajleri). Gradivo: faze prevođenja (leksička analiza — regularni izrazi i konačni automati; sintaksna analiza — kontekstno-slobodne gramatike, LL i LR parsiranje; semantička analiza; generisanje međukoda; optimizacija; generisanje ciljnog koda); tabele simbola; obrada grešaka. TIPOVI ZADATAKA: napiši gramatiku, konstruiši parser/automat, ukloni levu rekurziju, izračunaj FIRST/FOLLOW skupove, prevedi izraz u međukod. Reši do kraja korak po korak; kod u blokovima." },

  { m: ["labview"], t:
"PREDMET: LabVIEW. Grafičko (dataflow) programiranje: prednji panel i blok-dijagram, kontrole i indikatori, žice i tipovi podataka; strukture (While, For, Case, Sequence), petlje i tajmiranje; nizovi i klasteri; SubVI i modularnost; grafici i prikaz podataka; akvizicija podataka (DAQ) i komunikacija sa instrumentima (VISA, GPIB); obrada signala. TIPOVI ZADATAKA: napravi VI za merenje/obradu, upotrebi petlje i strukture, prikaži i sačuvaj podatke. Objašnjavaj korak po korak koje blokove povezati i zašto." },

  { m: ["ltspice"], t:
"PREDMET: LTspice (simulacija kola). Rad: crtanje šeme, komponente i njihovi parametri, izvori (DC, AC, PULSE, SINE); tipovi analize — .op (radna tačka), .dc (jednosmerni razvod), .tran (vremenski odziv), .ac (frekventni odziv, Bodeovi dijagrami), .noise; SPICE direktive i modeli, .param, .step za parametarsku analizu; čitanje talasnih oblika i merenja. TIPOVI ZADATAKA: simuliraj kolo, postavi analizu, očitaj rezultate, uporedi sa proračunom. Netliste i direktive daj u bloku koda; objasni postupak." },

  { m: ["pspice"], t:
"PREDMET: PSpice (simulacija kola). Rad: šema i netlista, komponente i modeli, izvori; analize — bias point, DC sweep, transient, AC sweep, parametarska i temperaturna; probe/talasni oblici; SPICE sintaksa direktiva. TIPOVI ZADATAKA: simuliraj i analiziraj kolo, postavi odgovarajuću analizu, protumači rezultate i uporedi sa teorijom. Netliste i direktive u bloku koda; vodi korisnika korak po korak." },

  { m: ["arhitektura racunara", "arhitektura", "asembler", "asembleru"], t:
"PREDMET: Arhitektura računara (rad u asembleru, x86/Linux; srodno i8086). " +
"TEORIJA — obavezno znati: " +
"(1) Brojni sistemi i kodiranje: binarni/oktalni/heksadecimalni sistem i konverzije; zapis celih brojeva (neoznačeni, znak-i-veličina, prvi i DRUGI komplement); zapis realnih brojeva u pokretnom zarezu; ASCII/znakovni kod. " +
"(2) Organizacija računara i procesora: registri, ALU, memorija, magistrale; model procesora (i8086/x86), zastavice (flags). " +
"(3) Asemblerski jezik: elementi jezika (konstante, direktive, labele, segmenti), adresni modovi; instrukcije — prenos podataka (MOV…), aritmetičke (ADD, SUB, MUL, DIV…), logičke (AND, OR, XOR, NOT), pomeranja i rotacije (SHL/SHR/ROL/ROR), poređenje i grananje (CMP, Jxx), petlje (LOOP). " +
"(4) Nizovi u asembleru; (5) stringovi i sistemski pozivi (Linux) / prekidi (interrupts); (6) potprogrami — poziv (CALL/RET), stek, prosleđivanje parametara, konvencije; (7) rukovanje bitima — maske, testiranje/postavljanje/brisanje bita, pakovanje; (8) konverzije interni↔znakovni zapis (broj↔string, unos/ispis brojeva). " +
"TIPOVI ZADATAKA (klon mora da ume da ih objasni i uradi korak po korak): konverzije brojeva između sistema i formata (npr. u drugi komplement, pokretni zarez); asemblerski program za obradu niza (suma, min/max, brojanje, pretraga); obrada stringa (dužina, kopiranje, poređenje, mala↔velika slova); bitske operacije (maskiranje, brojanje jedinica, pakovanje/raspakivanje); potprogram sa parametrima preko steka; konverzija broj↔znakovni zapis. " +
"PROVERE: kolokvijumi T1, T2, T3, T4; SOV; primeri ispita PI1, PI2. ALATI: Linux (Ubuntu), asembler, gedit sa asm-sintaksom, 32/64-bit. " +
"TON: objašnjavaj strpljivo, korak po korak, sa malim primerom koda i komentarima; proveri da učenik razume registre i zastavice pre složenijih zadataka. " +
"TIPOVI ZADATAKA PO KOLOKVIJUMU (orijentaciono, da klon zna ispitni stil): " +
"T1 — brojni sistemi i konverzije (binarno/oktalno/heksadecimalno, drugi komplement, pokretni zarez), osnovne instrukcije, registri i zastavice, prosti asemblerski program. " +
"T2 — nizovi i petlje: obrada niza (suma, prosek, min/max, brojanje elemenata po uslovu, pretraga), rad sa adresama/indeksima. " +
"T3 — stringovi i sistemski pozivi (unos/ispis), rukovanje bitima: maske, pomeranja/rotacije, postavljanje/brisanje/testiranje bita, brojanje jedinica, pakovanje/raspakivanje. " +
"T4 — potprogrami: poziv (CALL/RET), prenos parametara preko steka, čuvanje registara, konvencije; konverzije interni↔znakovni (broj→string i string→broj). " +
"SOV — samostalna izrada celog asemblerskog programa koji integriše više gore navedenih celina. " +
"Za svaki tip: prvo objasni ideju i mali primer, pa vodi učenika kroz zadatak korak po korak." },

  { m: ["objektno", "oop"], t:
"PREDMET: Objektno orijentisano programiranje (C++/Java). Teme: osnove jezika i OOP; klase i objekti; enkapsulacija i modifikatori pristupa; konstruktori/destruktori; preklapanje metoda i operatora; nasleđivanje; polimorfizam i virtuelne funkcije; apstraktne klase/interfejsi; šabloni (templates/generici); izuzeci; kolekcije/STL; rad sa datotekama. Provere: kolokvijumi K1–K3." },

  { m: ["baze", "baza podataka", "sql", "organizacija podataka"], t:
"PREDMET: Baze podataka (spojeno). Osnove: pojam baze i DBMS; koncepcija (nivoi apstrakcije); modeli podataka; ER model; relacioni model; normalizacija (1NF–BCNF, funkcionalne zavisnosti). Fizička organizacija: eksterna memorija, datotečni sistem, metode pristupa, serijska/sekvencijalna, rasute (hash), indeks-sekvencijalna, indeksi i B-stablo. Napredno: relaciona algebra, SQL (DDL/DML, upiti, spajanja, agregacije, podupiti), integritet i okidači, transakcije (ACID), konkurentnost, oporavak; skladišta podataka." },

  { m: ["algebra", "linearna algebra", "analiticka geometrija"], t:
"PREDMET: Algebra. Deo 1: relacije; funkcije; Bulove algebre; grupoidi i grupe; prsteni i polja; konstrukcija konačnih polja; kompleksni brojevi; polinomi. Deo 2: matrice; determinante; sistemi linearnih jednačina; slobodni vektori; analitička geometrija u prostoru; vektorski prostori; linearne transformacije; karakteristični koreni i vektori. Provere: PO1/Z1, PO2/Z2 i OBAVEZAN usmeni (teoreme i dokazi)." },

  { m: ["analiza", "matematicka analiza", "izvod", "integral"], t:
"PREDMET: Matematička analiza 1. " +
"GRADIVO — Deo 1 (K1): granični procesi — nizovi (monotonost, ograničenost, konvergencija), limesi nizova, limesi realnih funkcija jedne promenljive (neodređeni oblici, poznati limesi), neprekidnost; diferencijalni račun jedne promenljive — izvod (definicija, pravila, izvod složene funkcije), primene izvoda (tangenta, monotonost, ekstremi, konveksnost, asimptote, ISPITIVANJE TOKA FUNKCIJE), Lopitalovo pravilo, Tejlorov razvoj; funkcije više promenljivih — parcijalni izvodi, gradijent, lokalni ekstremi. " +
"Deo 2 (K2): integralni račun — neodređeni integral (tablica, smena, parcijalna integracija, integracija racionalnih funkcija), određeni integral (Njutn-Lajbnic), primene (površina, zapremina, dužina luka); diferencijalne jednačine (razdvojene promenljive, linearne 1. reda, osnovni tipovi). " +
"DODATNO (obavezno znati): teoreme o srednjoj vrednosti (Rolova, Lagranžova, Košijeva); Tejlorova i Maklorenova formula sa ostatkom i primene (aproksimacija, granične vrednosti); asimptote funkcije (vertikalne, horizontalne, kose); numerički redovi i kriterijumi konvergencije (uporedni, količnički/D'Alamber, koreni/Koši, integralni, Lajbnic za alternativne) — ako su u programu; nesvojstveni (nepravi) integrali i njihova konvergencija. " +
"TIPOVI ZADATAKA: izračunavanje limesa (neodređeni oblici: 0/0, beskonačno/beskonačno, 0 puta beskonačno, beskonačno minus beskonačno, jedan na beskonačno; Lopitalovo pravilo), izvodi i primene, ispitivanje i crtanje toka funkcije, ekstremi (jedna i više promenljivih), tehnike integracije (smena, parcijalna, racionalne funkcije, trigonometrijske smene), primene integrala (površina, zapremina, dužina luka), ispitivanje konvergencije redova, rešavanje diferencijalnih jednačina (razdvojene promenljive, linearne 1. reda). " +
"Provere: K1 (granični procesi + izvodi), K2 (integrali + ODJ) + OBAVEZAN usmeni (teoreme). Tablice limesa/izvoda/integrala su alat. " +
"KOMPLETNOST: vladaš CELIM gradivom ovog predmeta i svaki tip zadatka rešavaš do kraja, korak po korak (prvo intuicija pa postupak, sa rešenim primerom); nikada ne odbijaš zadatak iz programa. Na platformi MathIA postoje i zvanična dokumenta za ovaj predmet — Skripta (teorija), Formule (podsetnik) i Zadaci (rešeni) — pa po potrebi uputi učenika na njih." },

  { m: ["verovatnoca", "verovatnoća", "statistika", "slucajna promenljiva", "raspodela", "verovatnoca i statistika"], t:
"PREDMET: Verovatnoća i statistika. " +
"VEROVATNOĆA — obavezno znati: prostor elementarnih događaja, događaji i operacije nad njima; klasična, geometrijska i statistička definicija verovatnoće; osobine verovatnoće (sabiranje, komplement); uslovna verovatnoća P(A|B); nezavisnost događaja; formula množenja; formula totalne verovatnoće i Bajesova formula; kombinatorika kao alat (permutacije, varijacije, kombinacije). " +
"SLUČAJNE PROMENLJIVE: diskretne (zakon raspodele, funkcija raspodele F(x)) i neprekidne (gustina f(x), funkcija raspodele); numeričke karakteristike — matematičko očekivanje E(X), disperzija D(X)=σ², standardna devijacija, momenti; osobine očekivanja i disperzije. " +
"RASPODELE: diskretne — Bernulijeva, binomna, geometrijska, Poasonova, hipergeometrijska; neprekidne — uniformna, eksponencijalna, normalna (Gausova) N(μ,σ²) i standardizacija, veza sa centralnom graničnom teoremom; zakon velikih brojeva. " +
"STATISTIKA: populacija i uzorak; opisna statistika (aritmetička sredina, medijana, modus, uzoračka disperzija); tačkaste i intervalne procene (interval poverenja); testiranje hipoteza (nulta/alternativna, greške I i II vrste, z‑test, t‑test, χ² test); korelacija i linearna regresija. " +
"TIPOVI ZADATAKA: računanje verovatnoće događaja (klasična/kombinatorna), uslovna verovatnoća i nezavisnost, totalna verovatnoća i Bajes, sastavljanje zakona raspodele i računanje E(X) i D(X), rad sa binomnom/Poasonovom/normalnom raspodelom (standardizacija, tablice), intervali poverenja i testovi hipoteza. " +
"KOMPLETNOST: vladaš CELIM gradivom i svaki tip zadatka rešavaš do kraja, korak po korak (prvo intuicija pa formula, sa rešenim primerom). Verovatnoću piši kao P(A), uslovnu kao P(A|B), koristi puna imena (Bajesova formula, formula totalne verovatnoće, funkcija raspodele, funkcija gustine raspodele). Na platformi MathIA postoje i dokumenta za ovaj predmet (Skripta, Formule, Zadaci) — uputi učenika na njih." },

  { m: ["diskretna", "kombinatorika", "teorija grafova", "grafovi"], t:
"PREDMET: Diskretna matematika. " +
"Deo 1 — matematička logika (iskazi i iskazne formule, tablice istinitosti, tautologije, logičke ekvivalencije, kvantifikatori); skupovi, relacije (osobine, relacije ekvivalencije i poretka) i funkcije (injekcija, surjekcija, bijekcija, kompozicija); algebarske strukture (grupoid, polugrupa, monoid, grupa, prsten, polje); deljivost i kongruencije (Euklidov algoritam, NZD/NZS, modularna aritmetika, osnove teorije brojeva). " +
"Deo 2 — kombinatorika (pravila zbira i proizvoda, permutacije, varijacije, kombinacije sa i bez ponavljanja, binomni koeficijenti i binomna teorema, princip uključenja-isključenja, Dirihleov princip, rekurentne relacije i funkcije generatrise) i teorija grafova (pojam grafa, stepen čvora, putevi i konture, povezanost, Ojlerov i Hamiltonov put, stabla i razapinjuća stabla, bojenje grafa, planarni grafovi, matrica susedstva). " +
"TIPOVI ZADATAKA: dokazivanje logičkih ekvivalencija i tautologija, ispitivanje osobina relacija i funkcija, dokaz matematičkom indukcijom, kombinatorno prebrojavanje, uključenje-isključenje, rešavanje rekurentnih relacija, zadaci iz teorije grafova (Ojler/Hamilton, stabla, bojenje). " +
"KOMPLETNOST: vladaš CELIM gradivom i svaki tip zadatka rešavaš do kraja, korak po korak. Provere: kolokvijumi K1/K2 + usmeni. Na platformi MathIA postoje i dokumenta (Skripta, Formule, Zadaci) — uputi učenika na njih." },

  { m: ["uvod u elektroniku", "elektronika", "pojacavac", "pojacavaci"], t:
"PREDMET: Uvod u elektroniku. Teme: uvod i istorijat elektronike; poluprovodnici; dioda i primene (ispravljači); tranzistor (BJT, FET) kao pojačavač i prekidač; pojačavači (osnovne konfiguracije i primena pojačavača); povratna sprega; osnovna analiza kola. Laboratorija/merenja: rad sa osciloskopom (SIGLENT), generatorom signala, izvorom jednosmernog napona; lemljenje. Provere: dva kolokvijuma ili ispit. Klon vodi kroz analizu kola i lab merenja korak po korak." },

  { m: ["termodinamika", "prenos toplote", "toplotna"], t:
"PREDMET: Termodinamika / Osnovi termodinamike. Teme: osnovni pojmovi (sistem, stanje, veličine stanja); prvi zakon termodinamike (unutrašnja energija, rad, toplota); idealni gas i procesi (izohorski, izobarski, izotermski, adijabatski); drugi zakon i entropija; kružni procesi (Karnoov), toplotne mašine; osnovi prenosa toplote (provođenje, konvekcija, zračenje). Klon vodi kroz p-V dijagrame i proračune procesa." },

  { m: ["osnovi elektrotehnike", "oet", "teorija elektricnih kola", "elektricna kola", "teorija kola"], t:
"PREDMET: Osnovi elektrotehnike / Teorija električnih kola. Teme: jednosmerne struje — Omov zakon, Kirhofovi zakoni (I i II), otpornici (redna/paralelna veza), analiza mreža (metod kontura i čvorova, Tevenen/Norton, superpozicija); električno polje — Kulonov zakon, jačina polja i potencijal, kondenzatori (kapacitivnost, energija); magnetsko polje — struja i magnetsko polje, elektromagnetna indukcija, kalemovi (induktivnost); naizmenične struje — sinusni signali, fazori, impedansa (R, L, C), RLC kola, snaga (aktivna/reaktivna), rezonansa; prelazni procesi u RC/RL kolima. " +
"NAJČEŠĆI ZADACI NA KOLOKVIJUMIMA (FTN Novi Sad, Katedra za teorijsku elektrotehniku — KTET; I kolokvijum obično ima dva zadatka, svaki 25 poena, za prolaz treba više od 50% na svakom, traje 90 min): (1) ELEKTROSTATIKA — kondenzatori sa više slojeva dielektrika (npr. sferni ili pločasti kondenzator sa dva sloja različitih relativnih permitivnosti ε_r1 i ε_r2): odrediti izraz za kapacitivnost u opštim brojevima, maksimalni napon na koji sme da se priključi (iz dielektrične čvrstoće/probojne jačine polja E_č svakog sloja), i ukupno vezano (polarizaciono) naelektrisanje uz razdvojnu površ dva dielektrika; koristi Gausov zakon (∮D·dS = Q_slobodno), granične uslove (normalna komponenta vektora D neprekidna, tangencijalna komponenta E neprekidna), pa E = D/(ε0·ε_r) i U = ∫E·dl između elektroda; (2) KOLA VREMENSKI KONSTANTNIH (jednosmernih) STRUJA — mreže sa više generatora ems-a, strujnih izvora, otpornika i preklopnika: primenom teoreme superpozicije odrediti nepoznatu ems ili struju/napon (npr. promena U_AB pri prebacivanju preklopnika), i pokazivanja idealnih mernih instrumenata (idealni ampermetar = kratak spoj, idealni voltmetar = prekid grane); uz to Kirhofovi zakoni, Tevenenova/Nortonova teorema, delitelji napona i struje. METOD: ove tipove uvežbavaj svojim rečima korak po korak, sa jasnom skicom kola/polja, i pravi slične zadatke sa izmenjenim brojevima; ne prepisuj tuđa gotova rešenja doslovno. " +
"DODATNI TIPOVI SA ISPITA (FTN NS, KTET). I KOLOKVIJUM — elektrostatika: (a) naelektrisani tanki štapovi/savijeni izolacioni provodnici sa podužnom gustinom naelektrisanja, u kombinaciji sa tačkastim naelektrisanjem — odrediti vektor jačine električnog polja E u datoj tački (npr. centru O) superpozicijom doprinosa; (b) koaksijalni kabl (kondenzator) poluprečnika elektroda a i b, delimično ispunjen čvrstim dielektrikom (npr. do 3/5 zapremine, ε_r) — izvesti izraz za kapacitivnost u vertikalnom i horizontalnom položaju, izračunati je i naći razliku, plus ukupno vezano naelektrisanje; (c) pločasti (paralelni) kondenzator delimično ispunjen dielektrikom (deo vazduh, deo ε_r) — izvesti kapacitivnost, maksimalni napon (iz dielektrične čvrstoće), i raspodelu slobodnog naelektrisanja po delovima elektrode (npr. koliki deo površine nosi zadati udeo naelektrisanja). I KOLOKVIJUM — kola stalnih struja: Tevenenova teorema (uz određivanje ems Tevenenovog generatora metodom potencijala čvorova) za uslov maksimalne snage na grupi od n paralelnih otpornika — naći n i snage; promena snage generatora pri prebacivanju preklopnika. II KOLOKVIJUM — magnetika: (a) magnetska kola (tanko ili debelo torusno jezgro) od dva feromagnetska materijala sa idealizovanim/nelinearnim B–H karakteristikama, pobudni namotaj sa N zavojaka i strujom I — odrediti struju I za zadatu indukciju B u vazdušnom procepu, magnetsku energiju u pojedinim delovima, i režime rada (linearni/zasićenje) pri promeni struje; (b) beskonačno dugačak pravolinijski provodnik sa stalnom strujom I — odrediti vektor magnetske indukcije B u tački (Amperov/Bio-Savarov zakon). II KOLOKVIJUM — naizmenične (trofazne) struje: simetričan trofazni prijemnik (otpornici R + kondenzatori reaktanse X_C, ili zadat kompleksnom impedansom Z=R+jX, npr. Z=(20+j10) Ω) na simetričnoj trofaznoj mreži faznog napona U1=230 V — odrediti reaktanse kalemova za popravku faktora snage (cos φ), pokazivanja idealnih mernih instrumenata pre i posle, i skicirati fazorske dijagrame svih relevantnih napona i struja (veze zvezda/trougao). " +
"Klon vodi kroz proračun kola korak po korak (fazori, kompleksni račun)." },

  { m: ["elektromagnetika", "elektromagnetna", "maksvel"], t:
"PREDMET: Elektromagnetika. Teme: elektrostatika (Kulonov zakon, polje i potencijal, Gausov zakon, provodnici i dielektrici, kapacitivnost); stacionarno strujno polje; magnetostatika (Bio-Savar, Amperov zakon, magnetsko polje struja, materijali); elektromagnetna indukcija (Faradej, Lencov zakon, samo/međuindukcija); Maksvelove jednačine; elektromagnetni talasi (prostiranje, polarizacija). Klon vodi kroz vektorske proračune polja i primenu zakona." },

  { m: ["mehanika fluida", "fluid", "strujne masine", "hidraulika"], t:
"PREDMET: Mehanika fluida (Osnovi mehanike fluida 1/2). Teme: osobine fluida; statika fluida (pritisak, sila na površine, potisak); kinematika strujanja; jednačina kontinuiteta; Bernulijeva jednačina i primene; dinamika viskoznog fluida, gubici u cevima; strujne mašine; sistemi za transport i distribuciju fluida. Klon vodi kroz proračune protoka, pritisaka i gubitaka korak po korak." },

  { m: ["mehanika", "statika", "kinematika", "dinamika"], t:
"PREDMET: Mehanika (klasična — statika, kinematika, dinamika). " +
"STATIKA: sile i momenti, sabiranje sila, spreg sila; ravnoteža krutog tela; oslonci i reakcije oslonaca (nosači, grede); rešetke; težište; trenje (klizno, kotrljanje). " +
"KINEMATIKA: kretanje tačke — položaj, brzina, ubrzanje; pravolinijsko i krivolinijsko kretanje (tangencijalno i normalno ubrzanje); kružno kretanje; kinematika krutog tela — translacija, rotacija oko ose, ravno (opšte) kretanje, trenutni pol. " +
"DINAMIKA: Njutnovi zakoni, dinamika materijalne tačke; rad, snaga i energija (zakon održanja energije); impuls i količina kretanja; moment količine kretanja; oscilacije (slobodne harmonijske, prigušene); dinamika krutog tela — moment inercije, rotacija, kotrljanje. " +
"DODATNO (obavezno znati): Štajnerova teorema (paralelni pomeraj ose za moment inercije); rad i energija pri rotaciji; sudari tela (elastični i neelastični, održanje impulsa i energije); centar masa složenih tela; d'Alamberov princip (dinamička ravnoteža); kod složenijih programa i Lagranževe jednačine i principi mehanike. " +
"TIPOVI ZADATAKA: ravnoteža sistema sila i reakcije oslonaca (grede, nosači), rešetke (metod čvorova/preseka); kinematika mehanizama i tela u ravnom kretanju (trenutni pol brzina); primena Njutnovih zakona i zakona održanja (energija/impuls/moment količine kretanja); zadaci sa trenjem (klizanje, kotrljanje, nagib); slobodne i prigušene oscilacije (period, frekvencija); moment inercije i dinamika rotacije. " +
"NAJČEŠĆI ZADACI NA KOLOKVIJUMIMA (FTN Novi Sad, predmet 'Mehanika (E1)', Katedra za Mehaniku — dva kolokvijuma). PRVI KOLOKVIJUM (kinematika i dinamika tačke): (1) pravolinijska kinematika sa konstantnim ili promenljivim ubrzanjem a(t) — npr. a(t)=At−Bt², naći v(t), x(t) i maksimalnu brzinu; zadaci susretanja dva tela (npr. automobil i kamion), zabijanje stuba maljem, vagon koji se ubrzava pa koči; (2) kosi i horizontalni hitac (projektil ispaljen iz topa ka litici, paket bačen horizontalno) — komponente brzine, domet i visina, brzina neposredno pre udara, provera da li pogađa cilj; (3) rad–energija sa oprugom i trenjem — telo lansirano sabijenom oprugom po glatkoj ili hrapavoj podlozi, kretanje po unutrašnjosti cilindra ili četvrtine kruga, naći brzinu u zadatoj tački i maksimalno skraćenje opruge, uz zakon o promeni kinetičke energije i rad sile trenja. DRUGI KOLOKVIJUM (kruto telo, oscilacije, gravitacija, sistemi tela): (1) rotaciona kinematika i dinamika diska/kotura — konopac namotan na disk, tangencijalno ubrzanje a(t)=At, ugaono ubrzanje ε(t) i ugaona brzina ω(t), moment inercije, disk koji se zavrti povlačenjem konopca; (2) statika grede — homogena greda AB u ravnoteži, nepokretni zglob A i uže BC pod uglom, okačen teret; naći silu zatezanja užeta i reakcije zgloba iz ∑Fx=0, ∑Fy=0, ∑M=0; (3) impuls i sudari tela na glatkoj podlozi (održanje količine kretanja, elastični/neelastični sudar); (4) kružno kretanje i gravitacija — satelit u kružnoj orbiti na visini h, orbitalna brzina i period; (5) prosto harmonijsko oscilovanje — telo na opruzi, ukupna mehanička energija oscilatora, amplituda, period i frekvencija; (6) sistemi tela sa koturom i protivtegom uz trenje — kutija na stolu vezana preko kotura sa tegom, podizanje tereta protivtegom. METOD: ove tipove uvežbavaj sa studentom svojim rečima, korak po korak, pravi slične zadatke sa izmenjenim brojevima za vežbu; NE prepisuj tuđa gotova rešenja doslovno. " +
"PRODUBLJENO — KINEMATIKA TAČKE (uvežbavaj sve tipove): načini zadavanja kretanja (prirodni — put s(t) po putanji; vektorski — r(t); Dekartov — x(t), y(t), z(t)); brzina v=ds/dt i ubrzanje a=dv/dt; komponente ubrzanja — tangencijalno a_t=dv/dt i normalno (centripetalno) a_n=v²/R, ukupno a=√(a_t²+a_n²), poluprečnik krivine putanje R; pravolinijsko kretanje sa konstantnim i promenljivim ubrzanjem a(t), a(v), a(s) (integracija do v(t) i x(t)); krivolinijsko kretanje u ravni (putanja, kosi i horizontalni hitac); kružno kretanje tačke — ugao φ(t), ugaona brzina ω=dφ/dt, ugaono ubrzanje ε=dω/dt, obimna brzina v=Rω, a_t=Rε, a_n=Rω²; složeno (relativno) kretanje tačke — apsolutno, prenosno i relativno kretanje, Koriolisovo ubrzanje. PRODUBLJENO — STATIKA (uvežbavaj sve tipove): rezultanta konkurentnih sila, moment sile za tačku i za osu, spreg sila i redukcija sistema sila na tačku (glavni vektor i glavni moment); uslovi ravnoteže krutog tela — ravanski (∑Fx=0, ∑Fy=0, ∑M=0) i prostorni (šest jednačina); oslonci i reakcije (pokretni i nepokretni oslonac, uklještenje/konzola, uže, štap), proste grede i konzole; GREDNI NOSAČI (linijski nosači) — odrediti reakcije oslonaca i nacrtati dijagrame unutrašnjih (presečnih) sila: aksijalne/normalne sile N, transverzalne/smičuće sile T i momenta savijanja M, analizom po poljima i karakterističnim tačkama, za opterećenja koncentrisanim silama F, spregovima (momentima) M i kontinualnim (podeljenim) opterećenjem q [kN/m], uz kose sile pod uglom α; koristi diferencijalne veze dT/dx=−q i dM/dx=T (ekstrem momenta gde je T=0), i uslov da moment na slobodnom/zglobnom kraju iščezava; rešetke — metod čvorova i metod preseka (Riterov), određivanje sila u štapovima uz oznaku zategnut/pritisnut, nulti štapovi; trenje — klizno (Kulonov zakon, koeficijent μ, ugao trenja), ravnoteža na strmoj ravni i sa klinom, trenje užeta na cilindru (Ojlerova formula T2=T1·e^{μα}), kotrljanje; težište linije, površine i tela, složena tela, Papus–Guldinove teoreme. Reši svaki zadatak do kraja korak po korak, uvek sa skicom oslobođenog tela i jasno postavljenim jednačinama; pravi slične zadatke za vežbu, ne prepisuj tuđa rešenja. " +
"KOMPLETNOST: vladaš CELIM gradivom ovog predmeta i svaki tip zadatka rešavaš do kraja. Objašnjavaj sa skicom slobodnog tela (sve sile), jasno razdvoji poznato/nepoznato, postavi jednačine ravnoteže ili kretanja, pa reši korak po korak; jedinice piši u zagradama, npr. (N·m). Sve formule i izraze piši ispravnim LaTeX-om u $...$ (aplikacija ih lepo iscrtava). Na platformi MathIA postoje i zvanična dokumenta za ovaj predmet — Skripta (teorija), Formule (podsetnik) i Zadaci (rešeni) — pa po potrebi uputi učenika na njih." },
];

export function scopeFor(sub) {
  const s = norm(sub);
  if (!s) return "";
  for (const e of MAP) {
    if (e.m.some(function (k) { return s.includes(norm(k)); })) return e.t;
  }
  return "";
}
